## Schizophrenia (GSE74193)

In [2]:
import pandas as pd
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE74193_Schiz.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE74193_Schiz_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
(485512, 226)
(353, 226)

,ID_REF,Sample472,Sample636,Sample253,Sample263,Sample307,Sample363,Sample371,Sample526,Sample532,...,Sample269,Sample319,Sample430,Sample431,Sample229,Sample533,Sample315,Sample664,Sample642,Sample424
0,cg19945840,0.436069,0.462897,0.450668,0.423447,0.457814,0.436971,0.437309,0.426191,0.470651,...,0.448754,0.422785,0.488468,0.438915,0.431236,0.456215,0.458097,0.468187,0.471251,0.432891
1,cg13319175,0.494195,0.481286,0.495691,0.449325,0.495219,0.465146,0.531184,0.508756,0.547303,...,0.481532,0.488763,0.454202,0.596398,0.491685,0.449659,0.502258,0.512975,0.439693,0.511616

## AD (GSE80970, GSE66351, GSE109627)

In [3]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE80970_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE80970_AD_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
(485577, 149)
(353, 149)

,ID_REF,GSM2139439,GSM2139178,GSM2139208,GSM2139318,GSM2139334,GSM2139423,GSM2139311,GSM2139387,GSM2139360,...,GSM2139333,GSM2139364,GSM2139168,GSM2139385,GSM2139359,GSM2139391,GSM2139343,GSM2139351,GSM2139172,GSM2139290
0,cg19945840,0.42825,0.44328,0.48008,0.51024,0.46521,0.51908,0.51237,0.44207,0.49628,...,0.43111,0.45046,0.47098,0.42962,0.49273,0.45455,0.45120,0.40425,0.49285,0.49377
1,cg13319175,0.47016,0.55909,0.65875,0.55829,0.54668,0.52951,0.52409,0.45332,0.65270,...,0.46997,0.50216,0.61185,0.49501,0.62584,0.56846,0.48677,0.50838,0.57415,0.55016

In [4]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE66351_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE66351_AD_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
(481868, 107)
(353, 107)

,ID_REF,GSM2809030,GSM2808878,GSM2809044,GSM2809001,GSM2808875,GSM2808880,GSM2809040,GSM2808979,GSM2809048,...,GSM2808876,GSM2809064,GSM2808914,GSM2808933,GSM2809029,GSM2808939,GSM2809058,GSM2808982,GSM2808888,GSM2808884
0,cg19945840,0.4170,0.50743,0.46520,0.45878,0.32950,0.41868,0.45042,0.44804,0.46214,...,0.42751,0.49366,0.47776,0.34662,0.42591,0.46773,0.46141,0.46078,0.50923,0.52576
1,cg13319175,0.4123,0.38984,0.55132,0.56748,0.66756,0.45407,0.49159,0.57770,0.49541,...,0.47961,0.55592,0.39163,0.68368,0.57922,0.53658,0.53419,0.56304,0.36890,0.41712

In [ ]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE109627_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE109627_AD_Horvath.csv', index = False)
df1m.head(2)

## Other Diseased

In [6]:
# GSE40360_MS
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE40360_MS.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE40360_MS_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
(481917, 28)
(353, 28)

,ID_REF,GSM991991,GSM992001,GSM992005,GSM991997,GSM991994,GSM991988,GSM991987,GSM992000,GSM991989,...,GSM992012,GSM991999,GSM991993,GSM992010,GSM992011,GSM992008,GSM991995,GSM991986,GSM992003,GSM991998
0,cg19945840,0.477813,0.479656,0.534848,0.493139,0.416151,0.446016,0.449656,0.463984,0.487444,...,0.413613,0.454437,0.494902,0.470402,0.520776,0.505738,0.504620,0.475004,0.450994,0.401879
1,cg13319175,0.388313,0.443348,0.461779,0.380847,0.452341,0.446852,0.514370,0.427491,0.410009,...,0.369884,0.461041,0.411425,0.445339,0.458672,0.452539,0.327413,0.456804,0.427167,0.409900

In [7]:
# GSE53162_Auti
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE53162_Auti.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE53162_Auti_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
(485512, 20)
(353, 20)

,ID_REF,GSM1283236,GSM1283234,GSM1283250,GSM1283244,GSM1283254,GSM1283259,GSM1283265,GSM1283263,GSM1283264,GSM1283267,GSM1283261,GSM1283255,GSM1283238,GSM1283266,GSM1283253,GSM1283262,GSM1283239,GSM1283260,GSM1283241
0,cg19945840,0.415564,0.373039,0.418670,0.447239,0.417264,0.368792,0.419536,0.333239,0.293664,0.279152,0.341726,0.379900,0.430656,0.334327,0.377143,0.369115,0.387149,0.401823,0.387240
1,cg13319175,0.468233,0.407049,0.467932,0.414592,0.498656,0.511260,0.428259,0.491846,0.446662,0.490270,0.431165,0.503019,0.435229,0.482643,0.485651,0.472216,0.462084,0.479150,0.437857

In [8]:
# GSE59457_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE59457

dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE59457_HIV.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE59457_HIV_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
(485577, 24)
(353, 24)

,ID_REF,GSM1438133,GSM1438127,GSM1438135,GSM1438141,GSM1438142,GSM1438139,GSM1438130,GSM1438131,GSM1438134,...,GSM1438145,GSM1438143,GSM1438136,GSM1438132,GSM1438146,GSM1438138,GSM1438129,GSM1438144,GSM1438147,GSM1438149
0,cg19945840,0.391575,0.251663,0.417974,0.301857,0.427677,0.422707,0.439937,0.396080,0.394022,...,0.398998,0.443292,0.359562,0.372651,0.434802,0.434121,0.466836,0.327539,0.448831,0.352640
1,cg13319175,0.535402,0.390156,0.502301,0.540298,0.642751,0.562303,0.593768,0.490441,0.524772,...,0.537783,0.488372,0.463294,0.537928,0.457776,0.549507,0.538720,0.521518,0.579747,0.428153

In [9]:
# GSE67748_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67748

dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE67748_HIV.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67748_HIV_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
(485577, 8)
(353, 8)

,ID_REF,GSM1655148,GSM1655149,GSM1655150,GSM1655144,GSM1655145,GSM1655146,GSM1655147
0,cg19945840,0.331619,0.343266,0.386375,0.373248,0.380366,0.356329,0.227860
1,cg13319175,0.660441,0.573506,0.475671,0.543065,0.525675,0.570410,0.474092

In [13]:
# GSE67749_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67749

dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE67749.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67749_HIV_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
(485577, 34)
(353, 34)

,ID_REF,GSM1655152,GSM1655153,GSM1655154,GSM1655155,GSM1655156,GSM1655157,GSM1655158,GSM1655159,GSM1655160,...,GSM1655175,GSM1655176,GSM1655177,GSM1655178,GSM1655179,GSM1655180,GSM1655181,GSM1655182,GSM1655183,GSM1655184
0,cg19945840,0.503270,0.466699,0.461693,0.383559,0.413420,0.448738,0.459421,0.405235,0.553301,...,0.365219,0.451204,0.447910,0.376866,0.464112,0.488501,0.473209,0.521184,0.430739,0.330451
1,cg13319175,0.542434,0.647566,0.637101,0.555752,0.539088,0.556100,0.538890,0.546009,0.612954,...,0.563863,0.566366,0.463502,0.467953,0.563527,0.505592,0.550504,0.508390,0.475781,0.419436