## Schizophrenia (GSE74193)

In [1]:
import pandas as pd
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
    
dfh = pd.read_csv('CpG_347.csv')
df1 = pd.read_csv('GSE74193_Schiz.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE74193_Schiz_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
(485512, 226)
(347, 226)

,ID_REF,Sample472,Sample636,Sample253,Sample263,Sample307,Sample363,Sample371,Sample526,Sample532,...,Sample269,Sample319,Sample430,Sample431,Sample229,Sample533,Sample315,Sample664,Sample642,Sample424
0,cg00059225,0.201208,0.219521,0.172041,0.190833,0.20309,0.190754,0.194007,0.187365,0.196916,...,0.174035,0.223908,0.235794,0.181255,0.184525,0.200717,0.206203,0.218461,0.275843,0.171360
1,cg00088042,0.136404,0.159060,0.109329,0.126024,0.13474,0.138814,0.129317,0.144980,0.132356,...,0.108414,0.133422,0.146739,0.108386,0.115956,0.136002,0.123340,0.150468,0.179259,0.114607

## AD (GSE80970, GSE66351, GSE109627)

In [2]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
    
df1 = pd.read_csv('GSE80970_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE80970_AD_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
(485577, 149)
(347, 149)

,ID_REF,GSM2139439,GSM2139178,GSM2139208,GSM2139318,GSM2139334,GSM2139423,GSM2139311,GSM2139387,GSM2139360,...,GSM2139333,GSM2139364,GSM2139168,GSM2139385,GSM2139359,GSM2139391,GSM2139343,GSM2139351,GSM2139172,GSM2139290
0,cg00059225,0.21401,0.26570,0.28889,0.29091,0.29261,0.27307,0.29032,0.25745,0.29590,...,0.18963,0.26802,0.25091,0.25162,0.30433,0.28010,0.27043,0.23580,0.27994,0.3090
1,cg00088042,0.20784,0.21336,0.28179,0.24600,0.24410,0.25961,0.23198,0.20252,0.22029,...,0.18278,0.22092,0.21460,0.21486,0.31373,0.23044,0.19680,0.18855,0.19976,0.1877

In [3]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
    
df1 = pd.read_csv('GSE66351_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE66351_AD_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
(481868, 107)
(347, 107)

,ID_REF,GSM2809030,GSM2808878,GSM2809044,GSM2809001,GSM2808875,GSM2808880,GSM2809040,GSM2808979,GSM2809048,...,GSM2808876,GSM2809064,GSM2808914,GSM2808933,GSM2809029,GSM2808939,GSM2809058,GSM2808982,GSM2808888,GSM2808884
0,cg00059225,0.27372,0.21070,0.23993,0.21217,0.115910,0.23138,0.22455,0.24722,0.22731,...,0.26886,0.25074,0.24152,0.079711,0.212020,0.27114,0.20637,0.25849,0.27099,0.29502
1,cg00088042,0.14355,0.15714,0.16807,0.16196,0.068944,0.16483,0.14111,0.16726,0.15316,...,0.15381,0.21154,0.13887,0.088636,0.099978,0.15392,0.15100,0.11315,0.19199,0.21558

In [4]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
    
df1 = pd.read_csv('GSE109627_AD.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE109627_AD_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
(485512, 92)
(347, 92)

,ID_REF,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,SAMPLE_13,SAMPLE_14,...,SAMPLE_149,SAMPLE_150,SAMPLE_151,SAMPLE_152,SAMPLE_153,SAMPLE_155,SAMPLE_157,SAMPLE_158,SAMPLE_161,SAMPLE_162
0,cg00059225,0.249916,0.221825,0.228614,0.301278,0.315444,0.232762,0.256090,0.202662,0.295352,...,0.309981,0.216058,0.178497,0.219480,0.171836,0.279260,0.209277,0.275138,0.261038,0.176056
1,cg00088042,0.181171,0.176444,0.201923,0.181806,0.233661,0.165634,0.170459,0.160315,0.154977,...,0.105810,0.090275,0.085730,0.101532,0.099454,0.123388,0.144333,0.115741,0.113256,0.097376

## Other Diseased

In [5]:
# GSE53162_Auti
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
    
df1 = pd.read_csv('GSE53162_Auti.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE53162_Auti_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
(485512, 20)
(347, 20)

,ID_REF,GSM1283236,GSM1283234,GSM1283250,GSM1283244,GSM1283254,GSM1283259,GSM1283265,GSM1283263,GSM1283264,GSM1283267,GSM1283261,GSM1283255,GSM1283238,GSM1283266,GSM1283253,GSM1283262,GSM1283239,GSM1283260,GSM1283241
0,cg00059225,0.178339,0.133594,0.177821,0.125511,0.232952,0.142886,0.068620,0.080482,0.052959,0.084720,0.078911,0.145270,0.197618,0.077328,0.139019,0.061384,0.111145,0.179818,0.165700
1,cg00088042,0.115730,0.104611,0.102658,0.107402,0.108047,0.088733,0.055557,0.067256,0.076320,0.072689,0.074968,0.080288,0.108198,0.048661,0.079552,0.049867,0.093773,0.098451,0.082505

In [6]:
# GSE59457_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE59457

df1 = pd.read_csv('GSE59457_HIV.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE59457_HIV_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
(485577, 24)
(347, 24)

,ID_REF,GSM1438133,GSM1438127,GSM1438135,GSM1438141,GSM1438142,GSM1438139,GSM1438130,GSM1438131,GSM1438134,...,GSM1438145,GSM1438143,GSM1438136,GSM1438132,GSM1438146,GSM1438138,GSM1438129,GSM1438144,GSM1438147,GSM1438149
0,cg00059225,0.167315,0.049161,0.183147,0.067917,0.284485,0.245855,0.198210,0.18725,0.164284,...,0.169990,0.200214,0.151909,0.170559,0.191249,0.199485,0.190344,0.056176,0.209261,0.060185
1,cg00088042,0.098537,0.034183,0.095998,0.084706,0.108709,0.180793,0.114992,0.11471,0.104381,...,0.116596,0.130219,0.089517,0.098147,0.127370,0.113775,0.129927,0.085562,0.135241,0.065047

In [7]:
# GSE67748_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67748

df1 = pd.read_csv('GSE67748_HIV.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67748_HIV_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
(485577, 8)
(347, 8)

,ID_REF,GSM1655148,GSM1655149,GSM1655150,GSM1655144,GSM1655145,GSM1655146,GSM1655147
0,cg00059225,0.064130,0.066237,0.067262,0.067408,0.081603,0.064417,0.062447
1,cg00088042,0.062286,0.040940,0.028174,0.049042,0.082281,0.079036,0.039471

In [8]:
# GSE67749_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67749

df1 = pd.read_csv('GSE67749.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67749_HIV_Cortex.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
(485577, 34)
(347, 34)

,ID_REF,GSM1655152,GSM1655153,GSM1655154,GSM1655155,GSM1655156,GSM1655157,GSM1655158,GSM1655159,GSM1655160,...,GSM1655175,GSM1655176,GSM1655177,GSM1655178,GSM1655179,GSM1655180,GSM1655181,GSM1655182,GSM1655183,GSM1655184
0,cg00059225,0.165132,0.247280,0.196170,0.171560,0.169468,0.200407,0.211200,0.174159,0.258779,...,0.159728,0.256494,0.189571,0.135414,0.260871,0.186386,0.226518,0.261033,0.155389,0.085018
1,cg00088042,0.085047,0.150628,0.120359,0.083831,0.122689,0.091579,0.113586,0.078277,0.148806,...,0.124934,0.100786,0.126888,0.071301,0.161920,0.167693,0.112992,0.240791,0.155612,0.057379