## Schizophrenia (GSE74193)

In [2]:
import pandas as pd
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
    
dfh = pd.read_csv('236CpG_List.csv')
df1 = pd.read_csv('GSE74193_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE74193_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
(4604, 386)
(236, 386)

,CpG,Sample426,Sample152,Sample436,Sample75,Sample207,Sample391,Sample161,Sample673,Sample181,...,Sample82,Sample408,Sample115,Sample238,Sample189,Sample280,Sample291,Sample466,Sample602,Sample459
0,cg00302494,0.151802,0.138100,0.168174,0.108647,0.13802,0.166916,0.159934,0.188349,0.147942,...,0.099882,0.173129,0.119878,0.170735,0.169723,0.154732,0.206281,0.185974,0.160843,0.187404
1,cg00313401,0.158624,0.134106,0.160351,0.134305,0.16171,0.147064,0.145204,0.170409,0.154745,...,0.137575,0.160562,0.139107,0.162514,0.141571,0.172994,0.177030,0.184713,0.173248,0.179248

## AD (GSE80970, GSE66351, GSE109627)

In [3]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
    
df1 = pd.read_csv('GSE80970_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE80970_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
(4604, 139)
(236, 139)

,CpG,GSM2139230,GSM2139314,GSM2139249,GSM2139435,GSM2139234,GSM2139267,GSM2139347,GSM2139398,GSM2139373,...,GSM2139262,GSM2139448,GSM2139302,GSM2139315,GSM2139296,GSM2139244,GSM2139210,GSM2139286,GSM2139338,GSM2139198
0,cg00302494,0.30655,0.24545,0.23896,0.2086,0.17778,0.17351,0.17875,0.19579,0.20911,...,0.25074,NaN,0.17057,0.23736,0.24837,0.17375,0.24092,0.21247,0.16756,0.23791
1,cg00313401,0.20388,0.20702,0.17036,0.1767,0.18049,0.15155,0.21877,0.15390,0.15718,...,0.17492,0.17407,0.18066,0.19570,0.21641,0.18546,0.20905,0.20575,0.15653,0.19236

In [4]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
    
df1 = pd.read_csv('GSE66351_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE66351_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
(4585, 85)
(236, 85)

,CpG,GSM2809038,GSM2809056,GSM2808992,GSM2808909,GSM2809035,GSM2808961,GSM2808968,GSM2809021,GSM2809032,...,GSM2808950,GSM2809033,GSM2809057,GSM2809026,GSM2808959,GSM2809016,GSM2808924,GSM2808951,GSM2808972,GSM2809025
0,cg00302494,0.17880,0.14377,0.19549,0.16786,0.14409,0.14729,0.20908,0.14814,0.17478,...,0.13419,0.13210,0.18096,0.15439,0.14912,0.15585,0.17045,0.15570,0.15540,0.15637
1,cg00313401,0.14434,0.15966,0.18647,0.13608,0.12607,0.15215,0.20480,0.14461,0.16293,...,0.16044,0.14249,0.14552,0.14947,0.16843,0.19271,0.19333,0.15157,0.18772,0.12094

In [5]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE109627

df1 = pd.read_csv('GSE109627_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE109627_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
(4604, 72)
(236, 72)

,CpG,SAMPLE_4,SAMPLE_5,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_15,SAMPLE_16,SAMPLE_18,SAMPLE_22,...,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_147,SAMPLE_148,SAMPLE_154,SAMPLE_156,SAMPLE_159,SAMPLE_160
0,cg00302494,0.178341,0.241638,0.210506,0.193050,0.151342,0.163097,0.169727,0.233997,0.207981,...,0.201828,0.191491,0.181316,0.192604,0.162078,0.138666,0.166840,0.208961,0.187279,0.212168
1,cg00313401,0.210133,0.200568,0.214668,0.166294,0.161232,0.172791,0.173817,0.189767,0.190141,...,0.127911,0.160406,0.151823,0.156994,0.156439,0.142751,0.153085,0.164524,0.162545,0.182298

## Other Diseased

In [6]:
# GSE40360_MS
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
    
df1 = pd.read_csv('GSE40360_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE40360_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
(4604, 20)
(236, 20)

,CpG,GSM992030,GSM992020,GSM992019,GSM992027,GSM992022,GSM992021,GSM992015,GSM992014,GSM992023,GSM992025,GSM992029,GSM992024,GSM992016,GSM992018,GSM992017,GSM992031,GSM992028,GSM992026,GSM992032
0,cg00302494,0.156410,0.166547,0.142251,0.131727,0.133278,0.172727,0.149464,0.153676,0.173041,0.161331,0.144106,0.125680,0.155294,0.142947,0.145942,0.154388,0.149357,0.126959,0.185613
1,cg00313401,0.130448,0.125686,0.151088,0.154301,0.110457,0.156690,0.133546,0.140591,0.155360,0.157042,0.140540,0.139227,0.145525,0.154485,0.122400,0.132925,0.123209,0.116073,0.120937

In [7]:
# GSE53162_Auti
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
    
df1 = pd.read_csv('GSE53162_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE53162_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
(4604, 22)
(236, 22)

,CpG,GSM1283256,GSM1283269,GSM1283247,GSM1283273,GSM1283270,GSM1283237,GSM1283268,GSM1283257,GSM1283242,...,GSM1283240,GSM1283251,GSM1283252,GSM1283249,GSM1283235,GSM1283248,GSM1283245,GSM1283243,GSM1283258,GSM1283271
0,cg00302494,0.122681,0.056408,0.144995,0.090992,0.100840,0.132231,0.118385,0.130460,0.127147,...,0.141836,0.154938,0.144899,0.148363,0.111808,0.150017,0.120566,0.132865,0.141834,0.100367
1,cg00313401,0.149227,0.123045,0.145595,0.113373,0.135088,0.146819,0.156440,0.136693,0.156147,...,0.178626,0.132287,0.145307,0.129980,0.134556,0.149815,0.138352,0.139984,0.148218,0.149602

In [8]:
# GSE59457_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE59457

df1 = pd.read_csv('GSE59457_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE59457_236_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
(4604, 32)
(236, 32)

,CpG,GSM1438279,GSM1438226,GSM1438283,GSM1438165,GSM1438159,GSM1438223,GSM1438288,GSM1438167,GSM1438150,...,GSM1438184,GSM1438155,GSM1438163,GSM1438181,GSM1438178,GSM1438217,GSM1438289,GSM1438229,GSM1438151,GSM1438271
0,cg00302494,0.143340,0.142123,0.118431,0.155903,0.137718,0.103944,0.113785,0.105741,0.095905,...,0.134369,0.111588,0.141566,0.118326,0.119519,0.119364,0.138863,0.099588,0.109812,0.174567
1,cg00313401,0.103759,0.129336,0.110073,0.141099,0.123996,0.100484,0.108148,0.106462,0.122514,...,0.123047,0.131319,0.111282,0.183365,0.108051,0.141814,0.140842,0.098037,0.114691,0.095826

In [9]:
# GSE67748_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67748

df1 = pd.read_csv('GSE67748_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67748_236CpG_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
(4604, 13)
(236, 13)

,CpG,GSM1655134,GSM1655140,GSM1655136,GSM1655137,GSM1655141,GSM1655132,GSM1655143,GSM1655139,GSM1655138,GSM1655142,GSM1655133,GSM1655135
0,cg00302494,0.121975,0.088712,0.086915,0.100000,0.116358,0.095905,0.090996,0.092006,0.079702,0.089746,0.091042,0.113211
1,cg00313401,0.094586,0.123516,0.118544,0.095511,0.120991,0.122514,0.110617,0.110726,0.103474,0.113231,0.100192,0.124628

In [10]:
# GSE67749_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67749

df1 = pd.read_csv('GSE67749_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67749_236_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
(4604, 26)
(236, 26)

,CpG,GSM1655174,GSM1655175,GSM1655164,GSM1655171,GSM1655178,GSM1655166,GSM1655173,GSM1655167,GSM1655179,...,GSM1655180,GSM1655163,GSM1655168,GSM1655169,GSM1655161,GSM1655183,GSM1655162,GSM1655177,GSM1655160,GSM1655172
0,cg00302494,0.118431,0.113785,0.221888,0.207285,0.112768,0.208106,0.143340,0.236033,0.192210,...,0.146067,0.193042,0.241071,0.200162,0.236158,0.118565,0.211135,0.153764,0.193911,0.141566
1,cg00313401,0.110073,0.108148,0.210351,0.194151,0.117269,0.197389,0.103759,0.195377,0.097559,...,0.134061,0.185785,0.223834,0.181442,0.171164,0.145183,0.221375,0.123024,0.181772,0.111282

In [12]:
# GSE67749_HIV
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE64509

df1 = pd.read_csv('GSE64509_Top2b.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE64509_236_Healthy.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE64509
(4604, 261)
(236, 261)

,CpG,GSM1572882,GSM1573019,GSM1572853,GSM1573015,GSM1573046,GSM1573084,GSM1572856,GSM1572970,GSM1573007,...,GSM1573060,GSM1572927,GSM1573003,GSM1572915,GSM1573089,GSM1572967,GSM1573027,GSM1573049,GSM1572953,GSM1572914
0,cg00302494,0.149164,0.106634,0.109812,0.127247,0.134583,0.163576,0.149737,0.121975,0.178206,...,0.172713,0.126228,0.106892,0.145731,0.127423,0.148294,0.146787,0.192210,0.135186,0.085915
1,cg00313401,0.148959,0.114968,0.114691,0.139912,0.157557,0.123616,0.145305,0.094586,0.169525,...,0.148788,0.127898,0.103122,0.106202,0.090763,0.104884,0.141236,0.097559,0.142841,0.080082