In [1]:
import pandas as pd

## GSE40360

In [5]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
    
dfh = pd.read_csv('CpG_347.csv')
df1 = pd.read_csv('GSE40360_Control.csv')

print(dfh.shape)
df1.shape

Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
(347, 1)

(481917, 20)

In [6]:
df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE40360_Control_CpG_347.csv', index = False)
df1m.head(2)

(345, 20)

,ID_REF,GSM992030,GSM992020,GSM992019,GSM992027,GSM992022,GSM992021,GSM992015,GSM992014,GSM992023,GSM992025,GSM992029,GSM992024,GSM992016,GSM992018,GSM992017,GSM992031,GSM992028,GSM992026,GSM992032
0,cg00059225,0.214796,0.222942,0.229956,0.210757,0.188666,0.262891,0.257319,0.229304,0.267121,0.223869,0.222119,0.178477,0.286587,0.253583,0.218607,0.188135,0.219154,0.162356,0.230046
1,cg00088042,0.168397,0.159942,0.147492,0.160902,0.152026,0.142337,0.186856,0.161039,0.173973,0.189433,0.187737,0.150010,0.161223,0.131399,0.178172,0.129948,0.126036,0.096440,0.161854

## GSE53162

In [7]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
    
df1 = pd.read_csv('GSE53162_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE53162_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
(485512, 22)
(347, 22)

,ID_REF,GSM1283256,GSM1283269,GSM1283247,GSM1283273,GSM1283270,GSM1283237,GSM1283268,GSM1283257,GSM1283242,...,GSM1283240,GSM1283251,GSM1283252,GSM1283249,GSM1283235,GSM1283248,GSM1283245,GSM1283243,GSM1283258,GSM1283271
0,cg00059225,0.168973,0.065527,0.170136,0.076597,0.070348,0.185822,0.084207,0.145162,0.153269,...,0.200587,0.209383,0.136658,0.204447,0.156401,0.178311,0.150587,0.148347,0.191185,0.098340
1,cg00088042,0.131749,0.103033,0.091449,0.080424,0.059769,0.128286,0.070347,0.064680,0.101263,...,0.136469,0.121432,0.105605,0.123639,0.092974,0.118254,0.099522,0.073947,0.123000,0.063195

## GSE59457

In [8]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
    
df1 = pd.read_csv('GSE59457_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE59457_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
(485577, 32)
(347, 32)

,ID_REF,GSM1438279,GSM1438226,GSM1438283,GSM1438165,GSM1438159,GSM1438223,GSM1438288,GSM1438167,GSM1438150,...,GSM1438184,GSM1438155,GSM1438163,GSM1438181,GSM1438178,GSM1438217,GSM1438289,GSM1438229,GSM1438151,GSM1438271
0,cg00059225,0.182773,0.171431,0.128110,0.149605,0.135272,0.185645,0.159728,0.160552,0.054554,...,0.120568,0.107687,0.161329,0.141963,0.204964,0.152940,0.169250,0.083533,0.139473,0.188745
1,cg00088042,0.141725,0.122676,0.095645,0.141563,0.090394,0.110622,0.124934,0.142170,0.064182,...,0.116600,0.098039,0.085662,0.128168,0.164642,0.098227,0.127413,0.053706,0.100730,0.148103

## GSE61380

In [9]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE61380
    
df1 = pd.read_csv('GSE61380_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE61380_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE61380
(447273, 15)
(332, 15)

,ID_REF,GSM1503500,GSM1503525,GSM1503529,GSM1503502,GSM1503510,GSM1503511,GSM1503517,GSM1503501,GSM1503499,GSM1503508,GSM1503503,GSM1503507,GSM1503523,GSM1503512
0,cg00059225,0.179557,0.160007,0.117323,0.110547,0.111935,0.142001,0.151151,0.174445,0.145834,0.162498,0.160574,0.133797,0.102878,0.200234
1,cg00088042,0.085986,0.094452,0.095759,0.099269,0.062383,0.097491,0.148892,0.133665,0.101959,0.060804,0.070254,0.055455,0.072918,0.135357

## GSE61431

In [10]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE61431
    
df1 = pd.read_csv('GSE61431_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE61431_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE61431
(447904, 47)
(333, 47)

,ID_REF,6055432029_R04C02,6055432060_R06C01,6042316047_R04C01,6042316047_R02C02,6055432029_R01C02,6042316024_R01C02,6042316047_R06C01,6055432060_R02C02,6055432029_R06C01,...,6042316042_R06C01,6055432029_R06C02,6042316031_R03C01,6042316031_R05C01,6055432060_R05C01,6042316031_R01C02,6042316031_R04C01,6042316042_R02C02,6055432066_R04C01,6042316042_R03C02
0,cg00059225,0.198353,0.229993,0.109874,0.084048,0.196011,0.091551,0.100378,0.176691,0.220734,...,0.087301,0.248980,0.261311,0.128808,0.250735,0.090791,0.076793,0.096277,0.200327,0.072120
1,cg00088042,0.152811,0.118380,0.089670,0.166758,0.096471,0.076522,0.067676,0.152735,0.083184,...,0.084054,0.174972,0.115369,0.093146,0.143470,0.093311,0.105064,0.111907,0.120427,0.147658

## GSE64509

In [11]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE64509
    
df1 = pd.read_csv('GSE64509_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE64509_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE64509
(485577, 261)
(347, 261)

,ID_REF,GSM1572882,GSM1573019,GSM1572853,GSM1573015,GSM1573046,GSM1573084,GSM1572856,GSM1572970,GSM1573007,...,GSM1573060,GSM1572927,GSM1573003,GSM1572915,GSM1573089,GSM1572967,GSM1573027,GSM1573049,GSM1572953,GSM1572914
0,cg00059225,0.209288,0.180005,0.139473,0.067056,0.144500,0.244607,0.191178,0.059885,0.201800,...,0.23413,0.163633,0.119336,0.176325,0.165864,0.157430,0.174054,0.260871,0.175736,0.122672
1,cg00088042,0.154723,0.087849,0.100730,0.091056,0.118966,0.173606,0.089710,0.086187,0.201596,...,0.15531,0.103223,0.107296,0.139853,0.091321,0.094196,0.142703,0.161920,0.115367,0.099683

## GSE66351

In [12]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
    
df1 = pd.read_csv('GSE66351_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE66351_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
(481868, 85)
(347, 85)

,ID_REF,GSM2809038,GSM2809056,GSM2808992,GSM2808909,GSM2809035,GSM2808961,GSM2808968,GSM2809021,GSM2809032,...,GSM2808950,GSM2809033,GSM2809057,GSM2809026,GSM2808959,GSM2809016,GSM2808924,GSM2808951,GSM2808972,GSM2809025
0,cg00059225,0.22607,0.20099,0.21906,0.069537,0.173060,0.236560,0.28664,0.203050,0.25954,...,0.147100,0.15453,0.21519,0.18850,0.25219,0.24378,0.26868,0.22357,0.238970,0.19316
1,cg00088042,0.14451,0.12083,0.12909,0.087718,0.091332,0.094721,0.18711,0.085632,0.14630,...,0.004915,0.10735,0.13052,0.10623,0.13154,0.15531,0.16784,0.11573,0.089925,0.10247

## GSE67748

In [13]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
    
df1 = pd.read_csv('GSE67748_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67748_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
(485577, 13)
(347, 13)

,ID_REF,GSM1655134,GSM1655140,GSM1655136,GSM1655137,GSM1655141,GSM1655132,GSM1655143,GSM1655139,GSM1655138,GSM1655142,GSM1655133,GSM1655135
0,cg00059225,0.059885,0.054083,0.060304,0.061224,0.082501,0.054554,0.050213,0.056865,0.040542,0.061385,0.054615,0.069843
1,cg00088042,0.086187,0.096211,0.087072,0.090564,0.097014,0.064182,0.051349,0.051857,0.059148,0.057933,0.068446,0.101953

## GSE67749

In [14]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
    
df1 = pd.read_csv('GSE67749_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67749_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
(485577, 26)
(347, 26)

,ID_REF,GSM1655174,GSM1655175,GSM1655164,GSM1655171,GSM1655178,GSM1655166,GSM1655173,GSM1655167,GSM1655179,...,GSM1655180,GSM1655163,GSM1655168,GSM1655169,GSM1655161,GSM1655183,GSM1655162,GSM1655177,GSM1655160,GSM1655172
0,cg00059225,0.128110,0.159728,0.292160,0.248251,0.135414,0.301752,0.182773,0.277799,0.260871,...,0.186386,0.304278,0.326943,0.245566,0.287116,0.155389,0.291794,0.189571,0.258779,0.161329
1,cg00088042,0.095645,0.124934,0.200211,0.144243,0.071301,0.149364,0.141725,0.143823,0.161920,...,0.167693,0.209539,0.181487,0.124492,0.227722,0.155612,0.158351,0.126888,0.148806,0.085662

## GSE74193

In [15]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
    
df1 = pd.read_csv('GSE74193_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE74193_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
(485512, 386)
(347, 386)

,ID_REF,Sample426,Sample152,Sample436,Sample75,Sample207,Sample391,Sample161,Sample673,Sample181,...,Sample82,Sample408,Sample115,Sample238,Sample189,Sample280,Sample291,Sample466,Sample602,Sample459
0,cg00059225,0.196720,0.168518,0.178502,0.102182,0.153501,0.199626,0.149891,0.225385,0.15767,...,0.113346,0.219881,0.155782,0.190300,0.168670,0.200483,0.212387,0.238203,0.214261,0.213599
1,cg00088042,0.125176,0.111670,0.125516,0.080510,0.102455,0.132460,0.092327,0.142892,0.07881,...,0.084518,0.144370,0.084002,0.117237,0.095377,0.129314,0.097173,0.119689,0.123768,0.130422

## GSE76105

In [16]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE76105
    
df1 = pd.read_csv('GSE76105_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE76105_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE76105
(461272, 35)
(343, 35)

,ID_REF,GSM1974326,GSM1974357,GSM1974312,GSM1974320,GSM1974348,GSM1974364,GSM1974334,GSM1974359,GSM1974329,...,GSM1974302,GSM1974311,GSM1974338,GSM1974321,GSM1974352,GSM1974342,GSM1974356,GSM1974335,GSM1974313,GSM1974306
0,cg00059225,0.273188,0.252074,0.245905,0.187541,0.221883,0.193879,0.259272,0.261368,0.245122,...,0.233673,0.246090,0.253566,0.248514,0.297715,0.227361,0.257572,0.247668,0.22893,0.243805
1,cg00088042,0.130073,0.107974,0.095974,0.107535,0.140672,0.078567,0.160349,0.118340,0.124899,...,0.123626,0.080841,0.091955,0.097534,0.135059,0.137270,0.078861,0.074651,0.10372,0.089104

## GSE80970

In [17]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
    
df1 = pd.read_csv('GSE80970_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE80970_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
(485577, 139)
(347, 139)

,ID_REF,GSM2139230,GSM2139314,GSM2139249,GSM2139435,GSM2139234,GSM2139267,GSM2139347,GSM2139398,GSM2139373,...,GSM2139262,GSM2139448,GSM2139302,GSM2139315,GSM2139296,GSM2139244,GSM2139210,GSM2139286,GSM2139338,GSM2139198
0,cg00059225,0.26015,0.27388,0.24311,0.23443,0.26553,0.27328,0.30044,0.26796,0.22732,...,0.24125,0.30370,0.29008,0.29296,0.24351,0.25719,0.26566,0.25715,0.20390,0.28245
1,cg00088042,0.19151,0.21773,0.17058,0.17469,0.19009,0.18655,0.24202,0.16917,0.17955,...,0.19807,0.21259,0.19867,0.19782,0.22498,0.20917,0.22695,0.19145,0.15712,0.20985

## GSE89702

In [18]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE89702
    
df1 = pd.read_csv('GSE89702_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE89702_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE89702
(417039, 18)
(344, 18)

,ID_REF,GSM2387036,GSM2387045,GSM2387047,GSM2387023,GSM2387021,GSM2387052,GSM2387020,GSM2387025,GSM2387032,GSM2387040,GSM2387048,GSM2387037,GSM2387026,GSM2387046,GSM2387031,GSM2387042,GSM2387044
0,cg00059225,0.069189,0.116604,0.111927,0.063457,0.113664,0.080876,0.076446,0.070836,0.062099,0.089676,0.081562,0.082417,0.084717,0.063039,0.082869,0.168527,0.076187
1,cg00088042,0.068869,0.070865,0.072512,0.063375,0.069311,0.102599,0.079487,0.060872,0.062841,0.053736,0.091295,0.063848,0.074568,0.072047,0.070680,0.107173,0.107821

## GSE105109

In [19]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE105109
    
df1 = pd.read_csv('GSE105109_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE105109_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE105109
(367480, 109)
(310, 109)

,ID_REF,3998909040_R06C01,3999337016_R03C01,3999442078_R04C02,3999442017_R06C02,3998567066_R06C01,3999492090_R06C02,3998567071_R06C02,3998567102_R06C01,3999442036_R05C02,...,3998567055_R04C01,3998920160_R03C01,3999442017_R06C01,3998568002_R03C01,3998920136_R06C01,3998567107_R01C02,3999510116_R06C02,3998568002_R06C02,3999337016_R04C02,3999442017_R01C02
0,cg00059225,0.052324,0.126070,0.126345,0.178900,0.068635,0.188690,0.121722,0.052266,0.156396,...,0.053073,0.060514,0.147739,0.058492,0.055978,0.125755,0.099131,0.105348,0.139126,0.135034
1,cg00088042,0.055533,0.091478,0.054419,0.028357,0.061719,0.074856,0.060755,0.056003,0.057200,...,0.032951,0.062583,0.060855,0.078331,0.066019,0.077424,0.067921,0.038794,0.093963,0.052920

## GSE109627

In [20]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
    
df1 = pd.read_csv('GSE109627_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE109627_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
(485512, 72)
(347, 72)

,ID_REF,SAMPLE_4,SAMPLE_5,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_15,SAMPLE_16,SAMPLE_18,SAMPLE_22,...,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_147,SAMPLE_148,SAMPLE_154,SAMPLE_156,SAMPLE_159,SAMPLE_160
0,cg00059225,0.212128,0.296874,0.237522,0.232334,0.160885,0.187995,0.175179,0.305604,0.270017,...,0.202459,0.180852,0.202139,0.180471,0.203112,0.152953,0.205503,0.245246,0.263064,0.192456
1,cg00088042,0.188099,0.221302,0.202268,0.138928,0.151495,0.114095,0.144729,0.222151,0.209485,...,0.151861,0.138819,0.069175,0.109648,0.087859,0.105650,0.136637,0.131133,0.104534,0.143649

## GSE125895

In [21]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE125895
    
df1 = pd.read_csv('GSE125895_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE125895_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE125895
(420852, 188)
(339, 188)

,ID_REF,3-A08,2-A09,1-A11,4-C06,2-H06,3-B09,4-B02,1-C11,4-H01,...,1-H08,2-D02,1-C03,2-E02,4-G05,4-D02,2-D06,5-C12,2-E12,2-F04
0,cg00059225,0.079535,0.114931,0.089347,0.183388,0.212182,0.099511,0.117304,0.184374,0.216836,...,0.23403,0.213509,0.205539,0.212646,0.209168,0.172612,0.203339,0.191065,0.189207,0.228551
1,cg00088042,0.114529,0.088243,0.084367,0.145190,0.143018,0.118106,0.094087,0.128281,0.113578,...,0.14883,0.167859,0.109380,0.113387,0.105187,0.121932,0.111852,0.160750,0.119557,0.106134

## GSE134379

In [25]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
    
dfh = pd.read_csv('CpG_347.csv')
df1 = pd.read_csv('GSE134379_cb_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE134379_cb_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
(411157, 180)
(319, 180)

,CpG,CBL_0003,CBL_0015,CBL_0034,CBL_0038,CBL_0049,CBL_0053,CBL_0114,CBL_0123,CBL_0131,...,CBL_9929,CBL_9931,CBL_9944,CBL_9946,CBL_9947,CBL_9950,CBL_9954,CBL_9958,CBL_9959,CBL_9966
0,cg00059225,0.073946,0.087919,0.081358,0.058772,0.089896,0.081176,0.065738,0.054886,0.067012,...,0.098822,0.074606,0.052971,0.063376,0.082022,0.034235,0.085136,0.086789,0.077176,0.079373
1,cg00088042,0.084307,0.065365,0.045359,0.059301,0.090680,0.043450,0.065993,0.054236,0.069875,...,0.058604,0.069443,0.052751,0.057886,0.053738,0.041898,0.046559,0.133724,0.079781,0.048049

In [26]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
    
df1 = pd.read_csv('GSE134379_mtg_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE134379_mtg_Control_CpG_347.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
(389849, 180)
(310, 180)

,CpG,MTG_0627,MTG_9944,MTG_0151,MTG_9210,MTG_9638,MTG_9929,MTG_9737,MTG_9710,MTG_0823,...,MTG_0528,MTG_0847,MTG_0347,MTG_0328,MTG_0728,MTG_0872,MTG_0212,MTG_0123,MTG_0840,MTG_0718
0,cg00059225,0.247482,0.219897,0.246208,0.220016,0.233248,0.228383,0.246737,0.232251,0.220622,...,0.255318,0.209420,0.210303,0.235472,0.241686,0.306235,0.239948,0.274373,0.194222,0.236377
1,cg00088042,0.161975,0.123679,0.147943,0.125880,0.150885,0.131027,0.176270,0.140205,0.187241,...,0.161329,0.152098,0.178450,0.123033,0.150092,0.182580,0.164221,0.140127,0.106796,0.178590