In [2]:
import pandas as pd

## GSE40360

In [6]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE40360_Control.csv')

print(dfH.shape)
df1.shape

Z:\Project_Top2B\April_2023\Individual_Files\GSE40360
(353, 1)

(481917, 20)

In [11]:
df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE40360_Control_Horvath.csv', index = False)
df1m.head(2)

(353, 20)

,ID_REF,GSM992030,GSM992020,GSM992019,GSM992027,GSM992022,GSM992021,GSM992015,GSM992014,GSM992023,GSM992025,GSM992029,GSM992024,GSM992016,GSM992018,GSM992017,GSM992031,GSM992028,GSM992026,GSM992032
0,cg19945840,0.486432,0.466421,0.477010,0.527001,0.456031,0.485927,0.482889,0.460273,0.485439,0.471736,0.475664,0.476558,0.469960,0.486303,0.479235,0.420566,0.456071,0.448210,0.560369
1,cg13319175,0.429660,0.385390,0.417332,0.442866,0.481950,0.431773,0.477003,0.466848,0.427605,0.431280,0.443245,0.432335,0.453721,0.380552,0.481993,0.497649,0.398019,0.461259,0.459158

## GSE53162

In [12]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE53162_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE53162_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE53162
(485512, 22)
(353, 22)

,ID_REF,GSM1283256,GSM1283269,GSM1283247,GSM1283273,GSM1283270,GSM1283237,GSM1283268,GSM1283257,GSM1283242,...,GSM1283240,GSM1283251,GSM1283252,GSM1283249,GSM1283235,GSM1283248,GSM1283245,GSM1283243,GSM1283258,GSM1283271
0,cg19945840,0.428473,0.380515,0.405158,0.329785,0.349398,0.426618,0.390452,0.406731,0.420532,...,0.473416,0.471320,0.425786,0.495932,0.389580,0.416061,0.427588,0.395973,0.451338,0.382491
1,cg13319175,0.460103,0.562888,0.472785,0.392951,0.477423,0.424855,0.482077,0.513036,0.455358,...,0.485717,0.437572,0.502839,0.522099,0.436267,0.532262,0.448220,0.490262,0.484062,0.516563

## GSE59457

In [13]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE59457_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE59457_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE59457
(485577, 32)
(353, 32)

,ID_REF,GSM1438279,GSM1438226,GSM1438283,GSM1438165,GSM1438159,GSM1438223,GSM1438288,GSM1438167,GSM1438150,...,GSM1438184,GSM1438155,GSM1438163,GSM1438181,GSM1438178,GSM1438217,GSM1438289,GSM1438229,GSM1438151,GSM1438271
0,cg19945840,0.416492,0.442687,0.399369,0.409437,0.429314,0.414756,0.365219,0.424375,0.343651,...,0.373723,0.351113,0.445454,0.438205,0.452682,0.443636,0.394443,0.330675,0.413649,0.436955
1,cg13319175,0.560410,0.529053,0.556915,0.428167,0.585515,0.453249,0.563863,0.532482,0.482201,...,0.542776,0.591428,0.456035,0.504694,0.421028,0.465663,0.452009,0.561677,0.543216,0.633250

## GSE61380

In [14]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE61380
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE61380_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE61380_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE61380
(447273, 15)
(345, 15)

,ID_REF,GSM1503500,GSM1503525,GSM1503529,GSM1503502,GSM1503510,GSM1503511,GSM1503517,GSM1503501,GSM1503499,GSM1503508,GSM1503503,GSM1503507,GSM1503523,GSM1503512
0,cg19945840,0.386692,0.389616,0.369029,0.367720,0.342316,0.333398,0.412290,0.396693,0.333542,0.409993,0.366664,0.349846,0.378431,0.432126
1,cg13319175,0.466386,0.565482,0.519322,0.435021,0.499639,0.495175,0.424982,0.422316,0.450145,0.441669,0.422472,0.497430,0.396810,0.461318

## GSE61431

In [15]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE61431
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE61431_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE61431_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE61431
(447904, 47)
(345, 47)

,ID_REF,6055432029_R04C02,6055432060_R06C01,6042316047_R04C01,6042316047_R02C02,6055432029_R01C02,6042316024_R01C02,6042316047_R06C01,6055432060_R02C02,6055432029_R06C01,...,6042316042_R06C01,6055432029_R06C02,6042316031_R03C01,6042316031_R05C01,6055432060_R05C01,6042316031_R01C02,6042316031_R04C01,6042316042_R02C02,6055432066_R04C01,6042316042_R03C02
0,cg19945840,0.428171,0.452388,0.400231,0.380288,0.414145,0.375210,0.425443,0.438070,0.477902,...,0.391734,0.450009,0.422840,0.398515,0.453772,0.385630,0.382212,0.392998,0.453632,0.418231
1,cg13319175,0.624446,0.489039,0.666944,0.507830,0.593039,0.532875,0.636090,0.538601,0.541250,...,0.539965,0.567202,0.680815,0.459635,0.410150,0.584508,0.599604,0.554693,0.565776,0.543246

## GSE64509

In [16]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE64509
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE64509_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE64509_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE64509
(485577, 261)
(353, 261)

,ID_REF,GSM1572882,GSM1573019,GSM1572853,GSM1573015,GSM1573046,GSM1573084,GSM1572856,GSM1572970,GSM1573007,...,GSM1573060,GSM1572927,GSM1573003,GSM1572915,GSM1573089,GSM1572967,GSM1573027,GSM1573049,GSM1572953,GSM1572914
0,cg19945840,0.434029,0.402864,0.413649,0.376358,0.406655,0.463719,0.466485,0.324461,0.471845,...,0.458228,0.446231,0.387494,0.409816,0.434444,0.396625,0.435769,0.464112,0.430180,0.397878
1,cg13319175,0.416002,0.381057,0.543216,0.509037,0.523887,0.460539,0.490965,0.485916,0.528150,...,0.618641,0.461497,0.568041,0.434261,0.532666,0.584227,0.510651,0.563527,0.445669,0.372974

## GSE66351

In [17]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE66351_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE66351_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE66351
(481868, 85)
(353, 85)

,ID_REF,GSM2809038,GSM2809056,GSM2808992,GSM2808909,GSM2809035,GSM2808961,GSM2808968,GSM2809021,GSM2809032,...,GSM2808950,GSM2809033,GSM2809057,GSM2809026,GSM2808959,GSM2809016,GSM2808924,GSM2808951,GSM2808972,GSM2809025
0,cg19945840,0.40922,0.43417,0.43065,0.35672,0.34015,0.43081,0.50103,0.43579,0.44641,...,0.40333,0.37726,0.43141,0.41586,0.45214,0.42140,0.44422,0.43803,0.46586,0.43779
1,cg13319175,0.46768,0.50985,0.53841,0.70971,0.61693,0.50840,0.59281,0.44113,0.55934,...,0.51437,0.52908,0.57804,0.50640,0.55860,0.41718,0.38378,0.53940,0.52231,0.53753

## GSE67748

In [18]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE67748_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67748_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67748
(485577, 13)
(353, 13)

,ID_REF,GSM1655134,GSM1655140,GSM1655136,GSM1655137,GSM1655141,GSM1655132,GSM1655143,GSM1655139,GSM1655138,GSM1655142,GSM1655133,GSM1655135
0,cg19945840,0.324461,0.372478,0.377142,0.349973,0.396293,0.343651,0.251136,0.330103,0.270443,0.324558,0.288562,0.343323
1,cg13319175,0.485916,0.454947,0.522968,0.513257,0.473058,0.482201,0.500530,0.488625,0.413924,0.451723,0.499049,0.561853

## GSE67749

In [19]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE67749_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE67749_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE67749
(485577, 26)
(353, 26)

,ID_REF,GSM1655174,GSM1655175,GSM1655164,GSM1655171,GSM1655178,GSM1655166,GSM1655173,GSM1655167,GSM1655179,...,GSM1655180,GSM1655163,GSM1655168,GSM1655169,GSM1655161,GSM1655183,GSM1655162,GSM1655177,GSM1655160,GSM1655172
0,cg19945840,0.399369,0.365219,0.580283,0.578697,0.376866,0.516249,0.416492,0.533883,0.464112,...,0.488501,0.603068,0.577650,0.523138,0.540657,0.430739,0.512465,0.447910,0.553301,0.445454
1,cg13319175,0.556915,0.563863,0.639433,0.688392,0.467953,0.578446,0.560410,0.564557,0.563527,...,0.505592,0.572012,0.535296,0.646980,0.503443,0.475781,0.580481,0.463502,0.612954,0.456035

## GSE74193

In [20]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE74193_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE74193_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE74193
(485512, 386)
(353, 386)

,ID_REF,Sample426,Sample152,Sample436,Sample75,Sample207,Sample391,Sample161,Sample673,Sample181,...,Sample82,Sample408,Sample115,Sample238,Sample189,Sample280,Sample291,Sample466,Sample602,Sample459
0,cg19945840,0.466222,0.444712,0.446779,0.412691,0.448009,0.442764,0.441394,0.489643,0.438469,...,0.395794,0.450365,0.405782,0.452093,0.413834,0.435468,0.425311,0.427716,0.467025,0.449149
1,cg13319175,0.533562,0.425146,0.506661,0.458406,0.517485,0.453390,0.490680,0.490281,0.527367,...,0.450294,0.546798,0.438735,0.488168,0.520403,0.478652,0.619714,0.468459,0.509225,0.480814

## GSE76105

In [21]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE76105
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE76105_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE76105_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE76105
(461272, 35)
(352, 35)

,ID_REF,GSM1974326,GSM1974357,GSM1974312,GSM1974320,GSM1974348,GSM1974364,GSM1974334,GSM1974359,GSM1974329,...,GSM1974302,GSM1974311,GSM1974338,GSM1974321,GSM1974352,GSM1974342,GSM1974356,GSM1974335,GSM1974313,GSM1974306
0,cg19945840,0.500312,0.473752,0.497343,0.454684,0.494086,0.471719,0.488047,0.429589,0.513267,...,0.459462,0.443137,0.510776,0.473713,0.443773,0.491834,0.500308,0.499323,0.460666,0.489233
1,cg13319175,0.580298,0.527605,0.550145,0.474251,0.469723,0.508514,0.543816,0.580123,0.585978,...,0.522935,0.496654,0.541375,0.526832,0.540401,0.463694,0.482280,0.553472,0.451812,0.489299

## GSE80970

In [22]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE80970_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE80970_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE80970
(485577, 139)
(353, 139)

,ID_REF,GSM2139230,GSM2139314,GSM2139249,GSM2139435,GSM2139234,GSM2139267,GSM2139347,GSM2139398,GSM2139373,...,GSM2139262,GSM2139448,GSM2139302,GSM2139315,GSM2139296,GSM2139244,GSM2139210,GSM2139286,GSM2139338,GSM2139198
0,cg19945840,0.51767,0.50301,0.42189,0.49564,0.40995,0.43993,0.44393,0.39878,0.44597,...,0.43197,0.5151,0.51235,0.50446,0.45502,0.41264,0.49686,0.44836,0.42980,0.46868
1,cg13319175,0.61287,0.60230,0.47314,0.53525,0.47302,0.54012,0.48797,0.49281,0.48567,...,0.52558,0.5082,0.62744,0.54092,0.57107,0.41718,0.55973,0.55456,0.45391,0.57307

## GSE89702

In [23]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE89702
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE89702_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE89702_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE89702
(417039, 18)
(346, 18)

,ID_REF,GSM2387036,GSM2387045,GSM2387047,GSM2387023,GSM2387021,GSM2387052,GSM2387020,GSM2387025,GSM2387032,GSM2387040,GSM2387048,GSM2387037,GSM2387026,GSM2387046,GSM2387031,GSM2387042,GSM2387044
0,cg19945840,0.314692,0.350122,0.350431,0.260944,0.336445,0.299799,0.306388,0.313362,0.336304,0.350395,0.358928,0.345409,0.326028,0.385816,0.341581,0.366774,0.302748
1,cg13319175,0.511715,0.492773,0.508970,0.442131,0.559357,0.424153,0.486044,0.490272,0.427668,0.516986,0.482655,0.475806,0.472801,0.531814,0.530813,0.461700,0.441922

## GSE105109

In [24]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE105109
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE105109_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE105109_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE105109
(367480, 109)
(316, 109)

,ID_REF,3998909040_R06C01,3999337016_R03C01,3999442078_R04C02,3999442017_R06C02,3998567066_R06C01,3999492090_R06C02,3998567071_R06C02,3998567102_R06C01,3999442036_R05C02,...,3998567055_R04C01,3998920160_R03C01,3999442017_R06C01,3998568002_R03C01,3998920136_R06C01,3998567107_R01C02,3999510116_R06C02,3998568002_R06C02,3999337016_R04C02,3999442017_R01C02
0,cg19945840,0.278995,0.321525,0.355227,0.31414,0.292652,0.415597,0.196450,0.269692,0.391834,...,0.257707,0.248940,0.326336,0.258913,0.291503,0.290880,0.338877,0.281999,0.355672,0.299074
1,cg19420968,0.807434,0.764972,0.671068,0.61121,0.770391,0.678330,0.509516,0.799691,0.614895,...,0.803246,0.790438,0.876770,0.834416,0.790629,0.529097,0.810452,0.642167,0.635499,0.723357

## GSE109627

In [25]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE109627_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE109627_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE109627
(485512, 72)
(353, 72)

,ID_REF,SAMPLE_4,SAMPLE_5,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_15,SAMPLE_16,SAMPLE_18,SAMPLE_22,...,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_147,SAMPLE_148,SAMPLE_154,SAMPLE_156,SAMPLE_159,SAMPLE_160
0,cg19945840,0.486421,0.488341,0.484218,0.451761,0.457384,0.447660,0.452280,0.487311,0.499349,...,0.371351,0.404998,0.473722,0.444708,0.396193,0.452191,0.429753,0.474605,0.472110,0.45601
1,cg13319175,0.467667,0.566639,0.575781,0.489432,0.497335,0.490892,0.518092,0.597112,0.519110,...,0.380015,0.417691,0.453923,0.435480,0.394731,0.404289,0.444537,0.418540,0.439637,0.48476

## GSE125895

In [26]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE125895
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE125895_Control.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'ID_REF', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE125895_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE125895
(420852, 188)
(352, 188)

,ID_REF,3-A08,2-A09,1-A11,4-C06,2-H06,3-B09,4-B02,1-C11,4-H01,...,1-H08,2-D02,1-C03,2-E02,4-G05,4-D02,2-D06,5-C12,2-E12,2-F04
0,cg19945840,0.368680,0.361356,0.387070,0.422522,0.447955,0.396648,0.384709,0.395654,0.435409,...,0.448475,0.410021,0.417281,0.429781,0.410869,0.432732,0.375484,0.404352,0.416171,0.412817
1,cg13319175,0.452762,0.484597,0.495735,0.439141,0.411132,0.531853,0.472237,0.410181,0.446900,...,0.397289,0.558024,0.457687,0.402157,0.427795,0.438848,0.430011,0.401788,0.387864,0.394083

## GSE134379

In [29]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE134379_cb_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE134379_cb_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
(411157, 180)
(330, 180)

,CpG,CBL_0003,CBL_0015,CBL_0034,CBL_0038,CBL_0049,CBL_0053,CBL_0114,CBL_0123,CBL_0131,...,CBL_9929,CBL_9931,CBL_9944,CBL_9946,CBL_9947,CBL_9950,CBL_9954,CBL_9958,CBL_9959,CBL_9966
0,cg19945840,0.421007,0.427202,0.455135,0.392587,0.428056,0.443093,0.420321,0.446331,0.461590,...,0.419885,0.447816,0.403171,0.404175,0.401031,0.402324,0.378815,0.423241,0.480090,0.422957
1,cg13319175,0.526835,0.566065,0.572165,0.552861,0.546426,0.534324,0.531995,0.552591,0.598442,...,0.524054,0.575517,0.557682,0.507836,0.567853,0.599991,0.522057,0.587508,0.609452,0.566813

In [31]:
%cd Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
    
dfh = pd.read_csv('Horvath_353CpG.csv')
df1 = pd.read_csv('GSE134379_mtg_noPval.csv')
print(df1.shape)

df1m = pd.merge(dfh, df1, on = 'CpG', how = 'inner')
print(df1m.shape)
df1m.to_csv ('GSE134379_mtg_Control_Horvath.csv', index = False)
df1m.head(2)

Z:\Project_Top2B\April_2023\Individual_Files\GSE134379
(389849, 180)
(315, 180)

,CpG,MTG_0627,MTG_9944,MTG_0151,MTG_9210,MTG_9638,MTG_9929,MTG_9737,MTG_9710,MTG_0823,...,MTG_0528,MTG_0847,MTG_0347,MTG_0328,MTG_0728,MTG_0872,MTG_0212,MTG_0123,MTG_0840,MTG_0718
0,cg19945840,0.538472,0.488685,0.512767,0.530549,0.493746,0.529520,0.538440,0.518944,0.518842,...,0.543263,0.569864,0.453256,0.514271,0.565710,0.580828,0.612201,0.604895,0.541188,0.569381
1,cg13319175,0.560820,0.588263,0.611692,0.643452,0.611378,0.602202,0.611825,0.579403,0.558317,...,0.541526,0.600791,0.563110,0.581933,0.590545,0.592230,0.605910,0.553287,0.550573,0.660784