In [1]:
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\cerebellum

df1 = pd.read_csv('GSE53162_Top2b_cb.csv')
df2 = pd.read_csv('GSE134379_Top2b_cb.csv')
df3 = pd.read_csv('GSE89702_Top2b_cb.csv')
df4 = pd.read_csv('GSE67748_Top2b_cb.csv')
df5 = pd.read_csv('GSE59457_Top2b_cb.csv')
df6 = pd.read_csv('GSE61431_Top2b_cb.csv')
df7 = pd.read_csv('GSE105109_Top2b_cb.csv')
df8 = pd.read_csv('GSE125895_Top2b_cb.csv')
df9 = pd.read_csv('GSE64509_Top2b_cb.csv')

Z:\Project_Top2B\April_2023\regionwise\cerebellum

In [2]:
df1 = df1.transpose()
df1.columns = df1.iloc[0]
df1 = df1.iloc [1:, :]

df2 = df2.transpose()
df2.columns = df2.iloc[0]
df2 = df2.iloc [1:, :]

df3 = df3.transpose()
df3.columns = df3.iloc[0]
df3 = df3.iloc [1:, :]

df4 = df4.transpose()
df4.columns = df4.iloc[0]
df4 = df4.iloc [1:, :]

df5 = df5.transpose()
df5.columns = df5.iloc[0]
df5 = df5.iloc [1:, :]

df6 = df6.transpose()
df6.columns = df6.iloc[0]
df6 = df6.iloc [1:, :]

df7 = df7.transpose()
df7.columns = df7.iloc[0]
df7 = df7.iloc [1:, :]

df8 = df8.transpose()
df8.columns = df8.iloc[0]
df8 = df8.iloc [1:, :]

df9 = df9.transpose()
df9.columns = df9.iloc[0]
df9 = df9.iloc [1:, :]

In [4]:
df9.head()

Sample_ID,GSM1573031,GSM1572851,GSM1572961,GSM1572970,GSM1573012,GSM1572897,GSM1572963,GSM1573035,GSM1572923,GSM1573009,...,GSM1573015,GSM1573058,GSM1572962,GSM1572989,GSM1572999,GSM1573034,GSM1572997,GSM1573040,GSM1572850,GSM1573055
Age,15,38,53,53,58,59,59,63,64,64,...,100,100,101,101,111,111,112,112,114,114
cg00005072,0.856282,0.842625,0.787601,0.800803,0.845457,0.806316,0.821064,0.827314,0.816541,0.774609,...,0.780645,0.807024,0.781961,0.818405,0.837336,0.846445,0.782184,0.809696,0.83857,0.850369
cg00010266,0.059686,0.046472,0.063575,0.042558,0.035548,0.054085,0.058938,0.062931,0.065587,0.078744,...,0.052642,0.052962,0.05147,0.045688,0.049768,0.052735,0.048415,0.055094,0.055904,0.060575
cg00017203,0.840512,0.837088,0.811792,0.834134,0.850752,0.831086,0.819891,0.882874,0.857372,0.88234,...,0.846484,0.821054,0.837385,0.845117,0.824299,0.851083,0.868426,0.810073,0.865911,0.863218
cg00017489,0.116942,0.089849,0.133006,0.08264,0.077476,0.093779,0.067898,0.143993,0.09719,0.097661,...,0.100096,0.09943,0.101612,0.141697,0.094452,0.113636,0.099022,0.150834,0.104122,0.134368

In [5]:
from functools import reduce

df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9]

#df_merged = reduce(lambda left, right: pd.merge(left, right, on=['Sample_ID'], how='inner'), df_list)
df_merged = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='inner'), df_list)
df_merged.fillna('void', inplace=True)

# Drop columns containing ':' in their names
df_merged.drop([col for col in df_merged.columns if ':' in col], axis=1, inplace=True)

In [6]:
print(df_merged.shape)
df_merged.head(2)

(3311, 372)

Sample_ID,GSM1283273,GSM1283269,GSM1283272,GSM1283268,GSM1283270,GSM1283271,CBL_9526,CBL_9606,CBL_9827,CBL_0888,...,GSM1573015,GSM1573058,GSM1572962,GSM1572989,GSM1572999,GSM1573034,GSM1572997,GSM1573040,GSM1572850,GSM1573055
Age,2.000000,6.000000,21.000000,22.000000,23.000000,26.00000,63.000000,63.000000,63.000000,65.00000,...,100,100,101,101,111,111.000000,112,112,114.000000,114
cg00010266,0.073333,0.063563,0.060586,0.071251,0.062735,0.07783,0.029605,0.031991,0.039144,0.04291,...,0.052642,0.052962,0.05147,0.045688,0.049768,0.052735,0.048415,0.055094,0.055904,0.060575

In [8]:
df_merged.to_csv('Merged_Top2B_Cerebellum.csv')