In [1]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import seaborn as sns

In [2]:
%cd Z:\PPMI_Data\Excels\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
print(df.shape)
df.head(2)

Z:\PPMI_Data\Excels\Raw_And_More
(864067, 524)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272

#Top2B CPGs

In [4]:
%cd Z:\Project_Top2B\Clocks_Analysis\PD_PPMI
df_Top = pd.read_csv ("CpGLists_Top2B.csv")
print(df_Top.shape)
df_Top.head(2)

Z:\Project_Top2B\Clocks_Analysis\PD_PPMI
(4604, 1)

          CpG
0  cg00005072
1  cg00010266

In [5]:
df_TopM = pd.merge(df, df_Top, on='CpG', how='inner')
print(df_TopM.shape)
df_TopM.head(2)

(4603, 525)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg04794393,0.961282,0.967857,0.962830,0.964993,0.952825,0.973143,0.956331,0.970602,0.958041,...,0.958923,0.969337,0.965707,0.967372,0.961161,0.966463,0.969225,0.961829,0.967742,0.967758
1,cg17840536,0.953988,0.964030,0.970751,0.956355,0.937381,0.973718,0.904739,0.967452,0.970302,...,0.953809,0.972787,0.960556,0.964979,0.968184,0.942298,0.958113,0.956777,0.958559,0.953923

In [6]:
dft = df_TopM.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,4593,4594,4595,4596,4597,4598,4599,4600,4601,4602
CpG,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,cg15924509,cg16579225,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
200973410159_R03C01,0.961282,0.953988,0.904491,0.929923,0.737826,0.90154,0.922444,0.936642,0.040559,0.023157,...,0.324442,0.264352,0.582189,0.611364,0.326417,0.39107,0.493888,0.327762,0.226734,0.459956

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,cg15924509,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
0,CpG,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,cg15924509,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
1,200973410159_R03C01,0.961282,0.953988,0.904491,0.929923,0.737826,0.90154,0.922444,0.936642,0.040559,...,0.324442,0.264352,0.582189,0.611364,0.326417,0.39107,0.493888,0.327762,0.226734,0.459956

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,cg15924509,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
1,200973410159_R03C01,0.961282,0.953988,0.904491,0.929923,0.737826,0.90154,0.922444,0.936642,0.040559,...,0.324442,0.264352,0.582189,0.611364,0.326417,0.39107,0.493888,0.327762,0.226734,0.459956
2,200991620021_R01C01,0.967857,0.96403,0.867954,0.927103,0.709907,0.899323,0.906233,0.901101,0.033298,...,0.04056,0.018237,0.024238,0.028685,0.033769,0.031426,0.036924,0.171058,0.033119,0.086154

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,cg15924509,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
1,200973410159_R03C01,0.961282,0.953988,0.904491,0.929923,0.737826,0.90154,0.922444,0.936642,0.040559,...,0.324442,0.264352,0.582189,0.611364,0.326417,0.39107,0.493888,0.327762,0.226734,0.459956
2,200991620021_R01C01,0.967857,0.96403,0.867954,0.927103,0.709907,0.899323,0.906233,0.901101,0.033298,...,0.04056,0.018237,0.024238,0.028685,0.033769,0.031426,0.036924,0.171058,0.033119,0.086154

In [11]:
df2 = pd.read_csv ("Sentrix_Age_Methyl.csv")
df2.head(2)

               Sentrix  APPRDX   Age
0  200991620021_R01C01       1  65.1
1  200991620021_R03C01       1  67.6

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(458, 4606)

,Sentrix,APPRDX,Age,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
0,200991620021_R01C01,1,65.1,0.967857,0.96403,0.867954,0.927103,0.709907,0.899323,0.906233,...,0.04056,0.018237,0.024238,0.028685,0.033769,0.031426,0.036924,0.171058,0.033119,0.086154
1,200991620021_R03C01,1,67.6,0.96283,0.970751,0.901907,0.947444,0.770723,0.91536,0.906694,...,0.296777,0.398117,0.541346,0.575065,0.317647,0.415306,0.501171,0.436148,0.24004,0.489222

In [13]:
df_data = df3.drop(['Sentrix'], axis=1)
df_data.head(2)

,APPRDX,Age,cg04794393,cg17840536,cg19758750,cg09032281,cg02852398,cg15207968,cg12755103,cg05156582,...,cg04784122,cg17607496,cg09056691,cg25645693,cg10072574,cg00213853,cg09231482,cg00547789,cg10512285,cg04924141
0,1,65.1,0.967857,0.96403,0.867954,0.927103,0.709907,0.899323,0.906233,0.901101,...,0.04056,0.018237,0.024238,0.028685,0.033769,0.031426,0.036924,0.171058,0.033119,0.086154
1,1,67.6,0.96283,0.970751,0.901907,0.947444,0.770723,0.91536,0.906694,0.910982,...,0.296777,0.398117,0.541346,0.575065,0.317647,0.415306,0.501171,0.436148,0.24004,0.489222

In [14]:
df_data.to_csv('PPMI_Top2B.csv', index=False)

#Horvath1

In [15]:
%cd Z:\Project_Top2B\Clocks_Analysis\PD_PPMI
df_Hor = pd.read_csv ("Horvath1CpGs.csv")
print(df_Hor.shape)
df_Hor.head(2)

Z:\Project_Top2B\Clocks_Analysis\PD_PPMI
(353, 1)

          CpG
0  cg00075967
1  cg00374717

In [16]:
df_TopM = pd.merge(df, df_Hor, on='CpG', how='inner')
print(df_TopM.shape)
df_TopM.head(2)

(335, 525)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg13319175,0.916345,0.876005,0.881291,0.899211,0.867874,0.897708,0.871227,0.865747,0.869889,...,0.903454,0.874479,0.886547,0.903353,0.874404,0.901497,0.901106,0.904594,0.906945,0.900819
1,cg21211748,0.047419,0.030216,0.076499,0.034195,0.041080,0.039377,0.064212,0.030131,0.027508,...,0.042628,0.026849,0.032234,0.027519,0.032025,0.034256,0.031233,0.034991,0.039544,0.045187

In [17]:
dft = df_TopM.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,325,326,327,328,329,330,331,332,333,334
CpG,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,cg18983672,cg10266490,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
200973410159_R03C01,0.916345,0.047419,0.935816,0.113106,0.412038,0.416032,0.07991,0.026522,0.90115,0.163207,...,0.037849,0.057335,0.582441,0.456778,0.15122,0.020158,0.524586,0.041061,0.066466,0.038373

In [18]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [19]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,cg18983672,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
0,CpG,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,cg18983672,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
1,200973410159_R03C01,0.916345,0.047419,0.935816,0.113106,0.412038,0.416032,0.07991,0.026522,0.90115,...,0.037849,0.057335,0.582441,0.456778,0.15122,0.020158,0.524586,0.041061,0.066466,0.038373

In [20]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,cg18983672,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
1,200973410159_R03C01,0.916345,0.047419,0.935816,0.113106,0.412038,0.416032,0.07991,0.026522,0.90115,...,0.037849,0.057335,0.582441,0.456778,0.15122,0.020158,0.524586,0.041061,0.066466,0.038373
2,200991620021_R01C01,0.876005,0.030216,0.882283,0.220858,0.311121,0.383612,0.08713,0.06542,0.876671,...,0.058115,0.067406,0.522956,0.451959,0.136843,0.023174,0.498783,0.127253,0.147126,0.02406

In [21]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,cg18983672,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
1,200973410159_R03C01,0.916345,0.047419,0.935816,0.113106,0.412038,0.416032,0.07991,0.026522,0.90115,...,0.037849,0.057335,0.582441,0.456778,0.15122,0.020158,0.524586,0.041061,0.066466,0.038373
2,200991620021_R01C01,0.876005,0.030216,0.882283,0.220858,0.311121,0.383612,0.08713,0.06542,0.876671,...,0.058115,0.067406,0.522956,0.451959,0.136843,0.023174,0.498783,0.127253,0.147126,0.02406

In [22]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(458, 338)

,Sentrix,APPRDX,Age,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
0,200991620021_R01C01,1,65.1,0.876005,0.030216,0.882283,0.220858,0.311121,0.383612,0.08713,...,0.058115,0.067406,0.522956,0.451959,0.136843,0.023174,0.498783,0.127253,0.147126,0.02406
1,200991620021_R03C01,1,67.6,0.881291,0.076499,0.937541,0.160648,0.31384,0.467682,0.053909,...,0.054953,0.050002,0.508912,0.458011,0.113538,0.017405,0.544513,0.0972,0.14271,0.028032

In [23]:
df_data = df3.drop(['Sentrix'], axis=1)
print(df_data.shape)
df_data.head(2)

(458, 337)

,APPRDX,Age,cg13319175,cg21211748,cg19420968,cg14992253,cg26372517,cg07388493,cg19044674,cg23786576,...,cg07849904,cg01407797,cg19853760,cg23124451,cg19167673,cg11932564,cg26453588,cg26394940,cg13269407,cg17285325
0,1,65.1,0.876005,0.030216,0.882283,0.220858,0.311121,0.383612,0.08713,0.06542,...,0.058115,0.067406,0.522956,0.451959,0.136843,0.023174,0.498783,0.127253,0.147126,0.02406
1,1,67.6,0.881291,0.076499,0.937541,0.160648,0.31384,0.467682,0.053909,0.035863,...,0.054953,0.050002,0.508912,0.458011,0.113538,0.017405,0.544513,0.0972,0.14271,0.028032

In [24]:
df_data.to_csv('PPMI_Horvath.csv', index=False)