In [1]:
import pandas as pd

%cd Z:\Project_Top2B\April_2023\Cortex_Clock

df1 = pd.read_csv('GSE53162_Control_Cortex_Age.csv')
df2 = pd.read_csv('GSE59457_Control_Cortex_Age.csv')
df3 = pd.read_csv('GSE64509_Control_Cortex_Age.csv')
df4 = pd.read_csv('GSE66351_Control_Cortex_Age.csv')
df5 = pd.read_csv('GSE67748_Control_Cortex_Age.csv')
df6 = pd.read_csv('GSE67749_Control_Cortex_Age.csv')
df7 = pd.read_csv('GSE74193_Control_Cortex_Age.csv')
df8 = pd.read_csv('GSE80970_Control_Cortex_Age.csv')
df9 = pd.read_csv('GSE109627_Control_Cortex_Age.csv')

Z:\Project_Top2B\April_2023\Cortex_Clock

In [2]:
df1 = df1.transpose()
df1.columns = df1.iloc[0]
df1 = df1.iloc [1:, :]

df2 = df2.transpose()
df2.columns = df2.iloc[0]
df2 = df2.iloc [1:, :]

df3 = df3.transpose()
df3.columns = df3.iloc[0]
df3 = df3.iloc [1:, :]

df4 = df4.transpose()
df4.columns = df4.iloc[0]
df4 = df4.iloc [1:, :]

df5 = df5.transpose()
df5.columns = df5.iloc[0]
df5 = df5.iloc [1:, :]

df6 = df6.transpose()
df6.columns = df6.iloc[0]
df6 = df6.iloc [1:, :]

df7 = df7.transpose()
df7.columns = df7.iloc[0]
df7 = df7.iloc [1:, :]

df8 = df8.transpose()
df8.columns = df8.iloc[0]
df8 = df8.iloc [1:, :]

df9 = df9.transpose()
df9.columns = df9.iloc[0]
df9 = df9.iloc [1:, :]

df9.head(2)

ID_REF,SAMPLE_10,SAMPLE_102,SAMPLE_103,SAMPLE_105,SAMPLE_108,SAMPLE_11,SAMPLE_111,SAMPLE_112,SAMPLE_113,SAMPLE_114,...,SAMPLE_73,SAMPLE_77,SAMPLE_78,SAMPLE_83,SAMPLE_85,SAMPLE_88,SAMPLE_89,SAMPLE_93,SAMPLE_96,SAMPLE_99
Age,78,79,94,90,92,92,82,81,79,94,...,85,86,85,89,81,92,77,87,77,90
cg00059225,0.237522,0.177844,0.175379,0.144502,0.193957,0.232334,0.188997,0.221679,0.233177,0.236436,...,0.171985,0.194491,0.176526,0.268381,0.259044,0.260947,0.218921,0.217908,0.173148,0.189574

In [3]:
from functools import reduce

df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9]

df_merged = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='inner'), df_list)
df_merged.fillna('void', inplace=True)

df_merged.to_csv('Merged_Cortex_Healthy_Trans.csv')
print(df_merged.shape)
df_merged.head(2)

(348, 1027)

ID_REF,GSM1283235,GSM1283237,GSM1283240,GSM1283242,GSM1283243,GSM1283245,GSM1283246,GSM1283247,GSM1283248,GSM1283249,...,SAMPLE_73,SAMPLE_77,SAMPLE_78,SAMPLE_83,SAMPLE_85,SAMPLE_88,SAMPLE_89,SAMPLE_93,SAMPLE_96,SAMPLE_99
Age,22.000000,36.000000,56.000000,41.000000,19.000000,22.000000,36.000000,32.000000,50.000000,56.000000,...,85.000000,86.000000,85.000000,89.000000,81.000000,92.000000,77.000000,87.000000,77.000000,90.000000
cg00059225,0.156401,0.185822,0.200587,0.153269,0.148347,0.150587,0.213426,0.170136,0.178311,0.204447,...,0.171985,0.194491,0.176526,0.268381,0.259044,0.260947,0.218921,0.217908,0.173148,0.189574