In [1]:
import pandas as pd

%cd Z:\Project_Top2B\April_2023\Individual_Files\Horvath

df1 = pd.read_csv('GSE109627_Control_Horvath_Age.csv')
df2 = pd.read_csv('GSE80970_Control_Horvath_Age.csv')
df3 = pd.read_csv('GSE74193_Control_Horvath_Age.csv')
df4 = pd.read_csv('GSE67749_Control_Horvath_Age.csv')
df5 = pd.read_csv('GSE67748_Control_Horvath_Age.csv')
df6 = pd.read_csv('GSE66351_Control_Horvath_Age.csv')
df7 = pd.read_csv('GSE64509_Control_Horvath_Age.csv')
df8 = pd.read_csv('GSE59457_Control_Horvath_Age.csv')
df9 = pd.read_csv('GSE53162_Control_Horvath_Age.csv')
df10 = pd.read_csv('GSE40360_Control_Horvath_Age.csv')

Z:\Project_Top2B\April_2023\Individual_Files\Horvath

In [2]:
df1 = df1.transpose()
df1.columns = df1.iloc[0]
df1 = df1.iloc [1:, :]

df2 = df2.transpose()
df2.columns = df2.iloc[0]
df2 = df2.iloc [1:, :]

df3 = df3.transpose()
df3.columns = df3.iloc[0]
df3 = df3.iloc [1:, :]

df4 = df4.transpose()
df4.columns = df4.iloc[0]
df4 = df4.iloc [1:, :]

df5 = df5.transpose()
df5.columns = df5.iloc[0]
df5 = df5.iloc [1:, :]

df6 = df6.transpose()
df6.columns = df6.iloc[0]
df6 = df6.iloc [1:, :]

df7 = df7.transpose()
df7.columns = df7.iloc[0]
df7 = df7.iloc [1:, :]

df8 = df8.transpose()
df8.columns = df8.iloc[0]
df8 = df8.iloc [1:, :]

df9 = df9.transpose()
df9.columns = df9.iloc[0]
df9 = df9.iloc [1:, :]

df10 = df10.transpose()
df10.columns = df10.iloc[0]
df10 = df10.iloc [1:, :]

df10.head(2)

ID_REF,GSM992014,GSM992015,GSM992016,GSM992017,GSM992018,GSM992019,GSM992020,GSM992021,GSM992022,GSM992023,GSM992024,GSM992025,GSM992026,GSM992027,GSM992028,GSM992029,GSM992030,GSM992031,GSM992032
Age,54,76,71,72,79,59,73,64,58,68,54,66,68,58,64,81,71,53,71
cg19945840,0.460273,0.482889,0.46996,0.479235,0.486303,0.47701,0.466421,0.485927,0.456031,0.485439,0.476558,0.471736,0.44821,0.527001,0.456071,0.475664,0.486432,0.420566,0.560369

In [3]:
from functools import reduce

df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]

df_merged = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='inner'), df_list)
df_merged.fillna('void', inplace=True)

df_merged.to_csv('Merged_Horvath_Healthy_Trans.csv')
print(df_merged.shape)
df_merged.head(2)

(354, 1046)

ID_REF,SAMPLE_10,SAMPLE_102,SAMPLE_103,SAMPLE_105,SAMPLE_108,SAMPLE_11,SAMPLE_111,SAMPLE_112,SAMPLE_113,SAMPLE_114,...,GSM992023,GSM992024,GSM992025,GSM992026,GSM992027,GSM992028,GSM992029,GSM992030,GSM992031,GSM992032
Age,78.000000,79.000000,94.000000,90.000000,92.00000,92.000000,82.000000,81.000000,79.000000,94.000000,...,68.000000,54,66.000000,68.00000,58.000000,64.000000,81.000000,71.000000,53.000000,71.000000
cg19945840,0.484218,0.384874,0.373601,0.406892,0.45276,0.451761,0.361321,0.444439,0.435374,0.478193,...,0.485439,0.476558,0.471736,0.44821,0.527001,0.456071,0.475664,0.486432,0.420566,0.560369