In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\Project_Top2B\Clocks_Analysis\Analysis_PostNatal
df1 = pd.read_csv ("BorutaCommon_PostNatal_CpGList.csv")
df1.head(2)

Z:\Project_Top2B\Clocks_Analysis\Analysis_PostNatal

       ID_REF
0  cg00302494
1  cg00400263

In [3]:
%cd Z:\Project_Top2B\Clocks_Analysis\Analysis_PostNatal\Sample_Validate
Cpg_File = pd.read_csv ("sample_beta.csv")
print(Cpg_File.shape)
Cpg_File.head(3)

Z:\Project_Top2B\Clocks_Analysis\Analysis_PostNatal\Sample_Validate
(485577, 287)

,ID_REF,GSM2139163,GSM2139164,GSM2139165,GSM2139166,GSM2139167,GSM2139168,GSM2139169,GSM2139170,GSM2139171,...,GSM2139439,GSM2139440,GSM2139441,GSM2139442,GSM2139443,GSM2139444,GSM2139445,GSM2139446,GSM2139447,GSM2139448
0,cg00000029,0.59167,0.61134,0.52240,0.55689,0.66928,0.58430,0.65559,0.56454,0.59747,...,0.57535,0.53849,0.56029,0.54251,0.56040,0.56794,0.53911,0.56632,0.55618,0.61339
1,cg00000108,0.86955,0.87228,0.82742,0.89817,0.88524,0.87428,0.87558,0.87773,0.90295,...,0.85238,0.87738,0.87293,0.86766,0.86143,0.88927,0.89422,0.90161,0.86389,0.90964
2,cg00000109,0.71494,0.68538,0.74456,0.76460,0.74441,0.73426,0.75777,0.73569,0.76832,...,0.70521,0.74353,0.72854,0.69264,0.68510,0.74564,0.69255,0.75965,0.74891,0.75199

In [4]:
df = pd.merge (df1, Cpg_File, on = 'ID_REF', how = 'inner')
print(df.shape)
df.head(2)

(93, 287)

,ID_REF,GSM2139163,GSM2139164,GSM2139165,GSM2139166,GSM2139167,GSM2139168,GSM2139169,GSM2139170,GSM2139171,...,GSM2139439,GSM2139440,GSM2139441,GSM2139442,GSM2139443,GSM2139444,GSM2139445,GSM2139446,GSM2139447,GSM2139448
0,cg00302494,0.19419,0.19936,0.24864,0.19055,0.22473,0.23485,0.21308,0.23145,0.22805,...,0.20962,0.21084,0.20583,0.20598,0.22790,0.21956,0.22921,0.23893,0.21810,NaN
1,cg00400263,0.81514,0.80086,0.80285,0.80936,0.86210,0.83274,0.79445,0.75959,0.80886,...,0.77585,0.76618,0.76581,0.73631,0.75758,0.83940,0.82222,0.80937,0.82424,0.81298

In [5]:
df.to_csv ("sample_betaCpGTrans.csv",index = 'False')

In [6]:
Cpg_File1 = df.transpose()
Cpg_File1.head(2)

,0,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
ID_REF,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,cg03281661,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
GSM2139163,0.19419,0.81514,0.32503,0.31468,0.78239,0.3753,0.13906,0.25426,0.3748,0.13033,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.4688

In [7]:
Cpg_File1.rename(columns=Cpg_File1.iloc[0], inplace = True)
Cpg_File1.head(2)

,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,cg03281661,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
ID_REF,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,cg03281661,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
GSM2139163,0.19419,0.81514,0.32503,0.31468,0.78239,0.3753,0.13906,0.25426,0.3748,0.13033,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.4688

In [8]:
Cpg_File1.index.name ='ID'
Cpg_File1.reset_index(inplace=True)
Cpg_File1.head(2)

,ID,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
0,ID_REF,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
1,GSM2139163,0.19419,0.81514,0.32503,0.31468,0.78239,0.3753,0.13906,0.25426,0.3748,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.4688

In [9]:
Cpg_File1 = Cpg_File1.drop ([0], axis = 0)
Cpg_File1.head(2)

,ID,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,cg03066050,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
1,GSM2139163,0.19419,0.81514,0.32503,0.31468,0.78239,0.3753,0.13906,0.25426,0.3748,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.4688
2,GSM2139164,0.19936,0.80086,0.3187,0.36775,0.77689,0.31107,0.16176,0.26738,0.33088,...,0.27234,0.16996,0.86222,0.49586,0.22993,0.55134,0.12525,0.80986,0.09366,0.45393

In [10]:
Cpg_File1.to_csv ("sample_beta_CpGSort.csv",index = 'False')

In [14]:
df2 = pd.read_csv ("sample_beta_CpGSort.csv")
df2.head(2)

,ID,Age,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
0,GSM2139163,89,0.19419,0.81514,0.32503,0.31468,0.78239,0.37530,0.13906,0.25426,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.46880
1,GSM2139164,80,0.19936,0.80086,0.31870,0.36775,0.77689,0.31107,0.16176,0.26738,...,0.27234,0.16996,0.86222,0.49586,0.22993,0.55134,0.12525,0.80986,0.09366,0.45393

In [13]:
df1 = pd.read_csv ("sample_age_Cortex.csv")
df1.head(2)

           ID
0  GSM2139163
1  GSM2139164

In [15]:
df = pd.merge (df1, df2, on = 'ID', how = 'inner')
print(df.shape)
df.head(2)

(142, 95)

,ID,Age,cg00302494,cg00400263,cg00474746,cg00608548,cg01039763,cg01623261,cg01735384,cg02051616,...,cg24446586,cg24853724,cg26338030,cg26351776,cg26546105,cg26739510,cg26890189,cg27004760,cg27052113,cg27355141
0,GSM2139163,89,0.19419,0.81514,0.32503,0.31468,0.78239,0.37530,0.13906,0.25426,...,0.30507,0.16895,0.83776,0.51918,0.24859,0.57813,0.10909,0.79776,0.11486,0.46880
1,GSM2139164,80,0.19936,0.80086,0.31870,0.36775,0.77689,0.31107,0.16176,0.26738,...,0.27234,0.16996,0.86222,0.49586,0.22993,0.55134,0.12525,0.80986,0.09366,0.45393

In [16]:
df.to_csv ("sample_beta_CpGCortex.csv",index = 'False')