In [1]:
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\frontal_lobe\Diseased

df1 = pd.read_csv('GSE40360_Top2b_fl_MS.csv')
df2 = pd.read_csv('GSE53162_Top2b_fl_AD.csv')
df3 = pd.read_csv('GSE59457_Top2b_fl_HIV.csv')
df4 = pd.read_csv('GSE61380_Top2b_fl_Schiz.csv')
df5 = pd.read_csv('GSE61431_Top2b_fl_Schiz.csv')
df6 = pd.read_csv('GSE66351_Top2b_fl_AD.csv')
df7 = pd.read_csv('GSE67749_Top2b_fl_HIV.csv')
df8 = pd.read_csv('GSE74193_Top2b_fl_Schiz.csv')
df9 = pd.read_csv('GSE80970_Top2b_fl_AD.csv')
df10 = pd.read_csv('GSE125895_Top2b_fl_AD.csv')

Z:\Project_Top2B\April_2023\regionwise\frontal_lobe\Diseased

In [2]:
df1 = df1.transpose()
df1.columns = df1.iloc[0]
df1 = df1.iloc [1:, :]

df2 = df2.transpose()
df2.columns = df2.iloc[0]
df2 = df2.iloc [1:, :]

df3 = df3.transpose()
df3.columns = df3.iloc[0]
df3 = df3.iloc [1:, :]

df4 = df4.transpose()
df4.columns = df4.iloc[0]
df4 = df4.iloc [1:, :]

df5 = df5.transpose()
df5.columns = df5.iloc[0]
df5 = df5.iloc [1:, :]

df6 = df6.transpose()
df6.columns = df6.iloc[0]
df6 = df6.iloc [1:, :]

df7 = df7.transpose()
df7.columns = df7.iloc[0]
df7 = df7.iloc [1:, :]

df8 = df8.transpose()
df8.columns = df8.iloc[0]
df8 = df8.iloc [1:, :]

df9 = df9.transpose()
df9.columns = df9.iloc[0]
df9 = df9.iloc [1:, :]

df10 = df10.transpose()
df10.columns = df10.iloc[0]
df10 = df10.iloc [1:, :]

df10.head(2)

Sample_ID,1-C02,1-C05,1-C08,1-C09,1-C12,1-D04,1-D08,2-C05,2-C09,2-C12,...,2-D07,2-D10,3-C02,3-C09,3-D01,3-D12,4-C08,4-C09,4-D05,4-D09
Age,64.96,85.05,80.99,76.3,79.19,91.15,79.07,88.52,84.11,92.29,...,87.52,81.14,62.47,71.47,87.38,77.56,59.0,75.63,76.41,86.85
cg00005072,0.726166,0.592349,0.706681,0.606712,0.694807,0.693565,0.66703,0.71212,0.715737,0.642486,...,0.692704,0.710879,0.683547,0.650691,0.67516,0.645548,0.739323,0.713725,0.68038,0.747689

In [3]:
from functools import reduce

df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]

df_merged = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='inner'), df_list)
df_merged.fillna('void', inplace=True)

df_merged.to_csv('Merged_Top2B_Frontal_Diseased.csv')
print(df_merged.shape)
df_merged.head(2)

(4074, 438)

Sample_ID,GSM991986,GSM991987,GSM991988,GSM991989,GSM991990,GSM991991,GSM991992,GSM991993,GSM991994,GSM991995,...,2-D07,2-D10,3-C02,3-C09,3-D01,3-D12,4-C08,4-C09,4-D05,4-D09
Age,63,74,64,50,42,54,35,49,51,75,...,87.520000,81.140000,62.470000,71.470000,87.38000,77.560000,59.000000,75.630000,76.41000,86.850000
cg00005072,0.827303,0.841786,0.83719,0.873664,0.86283,0.861168,0.805556,0.864459,0.848574,0.879647,...,0.692704,0.710879,0.683547,0.650691,0.67516,0.645548,0.739323,0.713725,0.68038,0.747689