In [1]:
import pandas as pd

%cd Z:\Project_Top2B\April_2023\Horvath\Diseased

df1 = pd.read_csv('GSE67749_HIV_Horvath_Age.csv')
df2 = pd.read_csv('GSE67748_HIV_Horvath_Age.csv')
df3 = pd.read_csv('GSE59457_HIV_Horvath_Age.csv')
df4 = pd.read_csv('GSE53162_Auti_Horvath_Age.csv')
df5 = pd.read_csv('GSE40360_MS_Horvath_Age.csv')
df6 = pd.read_csv('AD_Horvath_Age.csv')
df7 = pd.read_csv('GSE74193_Schiz_Horvath_Age.csv')

Z:\Project_Top2B\April_2023\Horvath\Diseased

In [2]:
df1 = df1.transpose()
df1.columns = df1.iloc[0]
df1 = df1.iloc [1:, :]

df2 = df2.transpose()
df2.columns = df2.iloc[0]
df2 = df2.iloc [1:, :]

df3 = df3.transpose()
df3.columns = df3.iloc[0]
df3 = df3.iloc [1:, :]

df4 = df4.transpose()
df4.columns = df4.iloc[0]
df4 = df4.iloc [1:, :]

df5 = df5.transpose()
df5.columns = df5.iloc[0]
df5 = df5.iloc [1:, :]

df6 = df6.transpose()
df6.columns = df6.iloc[0]
df6 = df6.iloc [1:, :]

df7 = df7.transpose()
df7.columns = df7.iloc[0]
df7 = df7.iloc [1:, :]

df7.head(2)

ID_REF,Sample169,Sample173,Sample179,Sample184,Sample195,Sample196,Sample197,Sample204,Sample208,Sample209,...,Sample660,Sample663,Sample664,Sample665,Sample666,Sample667,Sample668,Sample669,Sample674,Sample675
Age,17.238356,18.016438,18.257534,18.578082,20.235616,20.235616,20.356164,21.254794,21.550684,21.550684,...,75.616438,80.249315,81.104109,81.210958,81.210958,83.19452,83.19452,83.460273,92.156164,96.980821
cg19945840,0.428253,0.442395,0.437104,0.444481,0.41557,0.447086,0.42357,0.420734,0.439055,0.450948,...,0.472962,0.479901,0.468187,0.467123,0.500104,0.438611,0.449901,0.489888,0.529108,0.479525

In [3]:
from functools import reduce

df_list = [df1, df2, df3, df4, df5, df6, df7]

df_merged = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='inner'), df_list)
df_merged.fillna('void', inplace=True)

df_merged.to_csv('Merged_Horvath_Diseased_Trans.csv')
print(df_merged.shape)
df_merged.head(2)

(354, 654)

ID_REF,GSM1655152,GSM1655153,GSM1655154,GSM1655155,GSM1655156,GSM1655157,GSM1655158,GSM1655159,GSM1655144,GSM1655145,...,Sample660,Sample663,Sample664,Sample665,Sample666,Sample667,Sample668,Sample669,Sample674,Sample675
Age,34.00000,61.000000,64.000000,27.000000,41.00000,52.000000,40.000000,33.000000,34.000000,61.000000,...,75.616438,80.249315,81.104109,81.210958,81.210958,83.194520,83.194520,83.460273,92.156164,96.980821
cg19945840,0.50327,0.466699,0.461693,0.383559,0.41342,0.448738,0.459421,0.405235,0.373248,0.380366,...,0.472962,0.479901,0.468187,0.467123,0.500104,0.438611,0.449901,0.489888,0.529108,0.479525