## Healthy

In [1]:
import csv
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE125895

df1 = pd.read_csv('GSE125895_Age_cb_hc.csv')
df2 = pd.read_csv('GSE125895_Top2b_Age.csv')
df2.head(2)

Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE125895

,Sample_ID,Age,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,1-A04,64.91,0.807901,0.067467,0.825659,0.129370,0.072238,0.880359,0.898375,0.072833,...,0.087869,0.834280,0.173457,0.154876,0.839205,0.905384,0.407477,0.114316,0.073078,0.834245
1,1-A09,52.61,0.803498,0.055310,0.821382,0.171889,0.080689,0.895274,0.900701,0.043921,...,0.085742,0.849105,0.184509,0.151830,0.834096,0.944170,0.386832,0.028045,0.076066,0.866834

In [2]:
merged_df = pd.merge(df1, df2, how ='inner', on = df1.columns[0])
merged_df.to_csv('GSE125895_Top2b_cb.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(43, 4239)

,Sample_ID,Age,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,2-A12,51.83,0.768422,0.064814,0.825704,0.113043,0.092687,0.879317,0.865177,0.069866,...,0.078768,0.909611,0.164772,0.141236,0.873717,0.908366,0.432961,0.107077,0.070274,0.868977
1,2-B06,51.94,0.799395,0.069136,0.842087,0.117971,0.094159,0.860965,0.866071,0.058192,...,0.089091,0.882550,0.213582,0.148099,0.834889,0.907561,0.407189,0.096272,0.069582,0.855082

## Diseased

In [1]:
import csv
import pandas as pd
%cd Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE125895
df1 = pd.read_csv('GSE125895_Age_cb_AD.csv')
df2 = pd.read_csv('GSE125895_AD_Top2b_Age.csv')

merged_df = pd.merge(df1, df2, how ='inner', on = df1.columns[0])
merged_df.to_csv('GSE125895_Top2b_AD_cb.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE125895
(24, 4240)

,Sample_ID,Age_x,Age_y,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,4-B10,58.41,58.41,0.802024,0.056846,0.832701,0.119714,0.078457,0.900108,0.850351,...,0.101774,0.875904,0.197723,0.155791,0.809493,0.935094,0.432322,0.076981,0.071834,0.826337
1,5-A02,59.00,59.00,0.765919,0.069411,0.824966,0.129910,0.092387,0.870637,0.885793,...,0.107013,0.905284,0.165310,0.118198,0.854526,0.883218,0.409929,0.127681,0.078830,0.834103