In [1]:
import csv
import pandas as pd

%cd Z:\Project_Top2B\April_2023\GSE134379

# Define the input and output file paths
input_file = "GSE134379_processedSamples_mtgAD.txt"
output_file = "GSE134379_mtg_AD.csv"

# Read the text file
with open(input_file, 'r') as f:
    lines = f.readlines()

# Create a list of lists, where each sublist represents a row in the CSV file
data = [line.strip().split() for line in lines]

# Write the data to the CSV file
with open(output_file, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(data)

Z:\Project_Top2B\April_2023\GSE134379

In [2]:
# Removing P val columns
# renaming columns

df = pd.read_csv('GSE134379_mtg_AD.csv')
df = df[df.columns.drop(list(df.filter(regex='Detection')))]
df.columns = df.columns.str.replace('Beta_value_for_', '')
print(df.shape)
df.head(2)

(389849, 226)

,CpG,MTG_0304,MTG_0889,MTG_0822,MTG_0805,MTG_0810,MTG_0848,MTG_0829,MTG_0830,MTG_0846,...,MTG_0764,MTG_0319,MTG_0054,MTG_0013,MTG_0537,MTG_0353,MTG_9604,MTG_9216,MTG_9708,MTG_0433
0,cg13869341,0.847850,0.897352,0.927881,0.917184,0.938105,0.877948,0.938322,0.931306,0.894391,...,0.832093,0.834346,0.893885,0.909658,0.845378,0.927252,0.941117,0.916523,0.895825,0.886957
1,cg14008030,0.719358,0.758621,0.749538,0.695128,0.771905,0.667136,0.782372,0.735174,0.748289,...,0.782364,0.771584,0.690381,0.789165,0.711638,0.659055,0.719719,0.738422,0.690326,0.774076

In [3]:
df2 = pd.read_csv('GSE134379_Age_MTG_AD.csv')
df2.head(2)

  Sample_ID  Age
0  MTG_0304   81
1  MTG_0889   84

In [4]:
# Extract the names which are present in both df2 and df
names = list(set(df2['Sample_ID']).intersection(set(df.columns)))

# Subset df using the names extracted from df2
df_subset = df[names]

# Adding CpG column from df
df_subset.insert(loc=0, column='CpG', value=df.iloc[:, 0])

df_subset.to_csv('GSE134379_mtg_noPval_AD.csv', index=False)

print(df_subset.shape)
df_subset.head(2)

(389849, 47)

,CpG,MTG_0637,MTG_0449,MTG_9739,MTG_0771,MTG_0830,MTG_0306,MTG_9722,MTG_0846,MTG_0022,...,MTG_9501,MTG_0008,MTG_0810,MTG_9921,MTG_0848,MTG_0889,MTG_0409,MTG_0822,MTG_0712,MTG_0665
0,cg13869341,0.877004,0.872694,0.926227,0.883123,0.931306,0.866734,0.880413,0.894391,0.823058,...,0.882561,0.828376,0.938105,0.919050,0.877948,0.897352,0.927435,0.927881,0.880831,0.928293
1,cg14008030,0.686505,0.704754,0.693045,0.764100,0.735174,0.713206,0.823145,0.748289,0.674746,...,0.741970,0.794669,0.771905,0.801202,0.667136,0.758621,0.735219,0.749538,0.687664,0.790949

## Subsetting only Top 2 beta associated CpGs

In [5]:
%cd Z:\Project_Top2B
df1 = pd.read_csv('CpGLists_Top2B.csv')

%cd Z:\Project_Top2B\April_2023\GSE134379
df2 = pd.read_csv('GSE134379_mtg_noPval_AD.csv')

print(df1.head(2))
df2.head(2)

Z:\Project_Top2B
Z:\Project_Top2B\April_2023\GSE134379
          CpG
0  cg00005072
1  cg00010266

,CpG,MTG_0637,MTG_0449,MTG_9739,MTG_0771,MTG_0830,MTG_0306,MTG_9722,MTG_0846,MTG_0022,...,MTG_9501,MTG_0008,MTG_0810,MTG_9921,MTG_0848,MTG_0889,MTG_0409,MTG_0822,MTG_0712,MTG_0665
0,cg13869341,0.877004,0.872694,0.926227,0.883123,0.931306,0.866734,0.880413,0.894391,0.823058,...,0.882561,0.828376,0.938105,0.919050,0.877948,0.897352,0.927435,0.927881,0.880831,0.928293
1,cg14008030,0.686505,0.704754,0.693045,0.764100,0.735174,0.713206,0.823145,0.748289,0.674746,...,0.741970,0.794669,0.771905,0.801202,0.667136,0.758621,0.735219,0.749538,0.687664,0.790949

In [6]:
# Merge df1 and df2 on the common column 'col1'
merged_df = pd.merge(df1, df2, on ='CpG', how ='inner')
merged_df.to_csv('GSE134379_Top2b_AD.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(3986, 47)

,CpG,MTG_0637,MTG_0449,MTG_9739,MTG_0771,MTG_0830,MTG_0306,MTG_9722,MTG_0846,MTG_0022,...,MTG_9501,MTG_0008,MTG_0810,MTG_9921,MTG_0848,MTG_0889,MTG_0409,MTG_0822,MTG_0712,MTG_0665
0,cg00005072,0.722690,0.730638,0.763438,0.868593,0.780274,0.732493,0.706062,0.765991,0.717039,...,0.739769,0.721859,0.755538,0.708679,0.806611,0.745061,0.685664,0.767757,0.769001,0.701621
1,cg00017203,0.906968,0.912626,0.851956,0.949850,0.866858,0.876884,0.872079,0.908971,0.870722,...,0.849174,0.889253,0.853374,0.824915,0.844569,0.905847,0.866818,0.878229,0.863072,0.893700

In [8]:
%cd Z:\Project_Top2B\April_2023\GSE134379
import pandas as prash

df1 = prash.read_csv('GSE134379_Age_MTG_AD.csv')
df2 = prash.read_csv('GSE134379_Top2b_AD.csv')

print(df1.head(2))
df2.head(2)

Z:\Project_Top2B\April_2023\GSE134379
  Sample_ID  Age
0  MTG_0304   81
1  MTG_0889   84

,Unnamed: 0,CpG,MTG_0637,MTG_0449,MTG_9739,MTG_0771,MTG_0830,MTG_0306,MTG_9722,MTG_0846,...,MTG_9501,MTG_0008,MTG_0810,MTG_9921,MTG_0848,MTG_0889,MTG_0409,MTG_0822,MTG_0712,MTG_0665
0,0,cg00005072,0.722690,0.730638,0.763438,0.868593,0.780274,0.732493,0.706062,0.765991,...,0.739769,0.721859,0.755538,0.708679,0.806611,0.745061,0.685664,0.767757,0.769001,0.701621
1,1,cg00017203,0.906968,0.912626,0.851956,0.949850,0.866858,0.876884,0.872079,0.908971,...,0.849174,0.889253,0.853374,0.824915,0.844569,0.905847,0.866818,0.878229,0.863072,0.893700

In [9]:
# Merge df1 and df2 on the common column 'col1'
merged_df = prash.merge(df1, df2, left_on ='Sample', right_on = 'CpG', how ='inner')
merged_df.to_csv('GSE134379_mtg_Top2b_Age_AD.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

KeyError: 'Sample'