In [1]:
%cd Z:\Project_Top2B\April_2023\GSE53162
import pandas as pd

Z:\Project_Top2B\April_2023\GSE53162

In [2]:
df2 = pd.read_csv('GSE53162_Age_Auti.csv')
df2.head(2)

    Sample_ID  Age
0  GSM1283234   16
1  GSM1283236   29

In [3]:
df = pd.read_csv('GSE53162.csv')

# remove quotes from column names
df.columns = df.columns.str.replace('"', '')

# remove quotes from cell values
df = df.applymap(lambda x: x.replace('"', '') if isinstance(x, str) else x)

# print updated DataFrame
print(df.shape)
df.head(2)

(485512, 41)

,ID_REF,GSM1283234,GSM1283235,GSM1283236,GSM1283237,GSM1283238,GSM1283239,GSM1283240,GSM1283241,GSM1283242,...,GSM1283264,GSM1283265,GSM1283266,GSM1283267,GSM1283268,GSM1283269,GSM1283270,GSM1283271,GSM1283272,GSM1283273
0,cg00000029,0.493948,0.460208,0.505294,0.527448,0.518413,0.513362,0.514097,0.484241,0.498951,...,0.775312,0.715112,0.708935,0.734980,0.702218,0.694026,0.721871,0.689381,0.670400,0.801641
1,cg00000108,0.906888,0.881898,0.882825,0.895423,0.904080,0.868749,0.868257,0.925761,0.890180,...,0.275051,0.436430,0.379023,0.527408,0.339163,0.640692,0.376772,0.596968,0.482333,0.478636

In [4]:
# Extract the names which are present in both df2 and df
names = list(set(df2['Sample_ID']).intersection(set(df.columns)))

# Subset df using the names extracted from df2
df_subset = df[names]

# Adding CpG column from df
df_subset.insert(loc=0, column='ID_REF', value=df.iloc[:, 0])

df_subset.to_csv('GSE53162_Auti.csv', index=False)

print(df_subset.shape)
df_subset.head(2)

(485512, 20)

,ID_REF,GSM1283236,GSM1283234,GSM1283250,GSM1283244,GSM1283254,GSM1283259,GSM1283265,GSM1283263,GSM1283264,GSM1283267,GSM1283261,GSM1283255,GSM1283238,GSM1283266,GSM1283253,GSM1283262,GSM1283239,GSM1283260,GSM1283241
0,cg00000029,0.505294,0.493948,0.564149,0.636141,0.417569,0.540484,0.715112,0.658969,0.775312,0.734980,0.742752,0.454557,0.518413,0.708935,0.530057,0.689102,0.513362,0.421466,0.484241
1,cg00000108,0.882825,0.906888,0.885342,0.887788,0.896091,0.921768,0.436430,0.522276,0.275051,0.527408,0.298963,0.907656,0.904080,0.379023,0.922893,0.475604,0.868749,0.880555,0.925761

In [5]:
import pandas as pd

%cd Z:\Project_Top2B
df1 = pd.read_csv('CpGLists_Top2B.csv')

%cd Z:\Project_Top2B\April_2023\GSE53162
df2 = pd.read_csv('GSE53162_Auti.csv')

print(df1.head(2))
df2.head(2)

Z:\Project_Top2B
Z:\Project_Top2B\April_2023\GSE53162
          CpG
0  cg00005072
1  cg00010266

,ID_REF,GSM1283236,GSM1283234,GSM1283250,GSM1283244,GSM1283254,GSM1283259,GSM1283265,GSM1283263,GSM1283264,GSM1283267,GSM1283261,GSM1283255,GSM1283238,GSM1283266,GSM1283253,GSM1283262,GSM1283239,GSM1283260,GSM1283241
0,cg00000029,0.505294,0.493948,0.564149,0.636141,0.417569,0.540484,0.715112,0.658969,0.775312,0.734980,0.742752,0.454557,0.518413,0.708935,0.530057,0.689102,0.513362,0.421466,0.484241
1,cg00000108,0.882825,0.906888,0.885342,0.887788,0.896091,0.921768,0.436430,0.522276,0.275051,0.527408,0.298963,0.907656,0.904080,0.379023,0.922893,0.475604,0.868749,0.880555,0.925761

In [6]:
# Merge df1 and df2 on the common column 'col1'
merged_df = pd.merge(df1, df2, how ='inner', left_on='CpG', right_on='ID_REF')

# Drop the common column 'ID_REF'
merged_df.drop('ID_REF', axis=1, inplace=True)
merged_df.to_csv('GSE53162_Auti_Top2b.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(4604, 20)

,CpG,GSM1283236,GSM1283234,GSM1283250,GSM1283244,GSM1283254,GSM1283259,GSM1283265,GSM1283263,GSM1283264,GSM1283267,GSM1283261,GSM1283255,GSM1283238,GSM1283266,GSM1283253,GSM1283262,GSM1283239,GSM1283260,GSM1283241
0,cg00005072,0.727061,0.707072,0.722991,0.735139,0.718180,0.689318,0.818405,0.772164,0.812461,0.844410,0.824755,0.670074,0.734825,0.810229,0.631231,0.787976,0.708073,0.669168,0.667346
1,cg00010266,0.075801,0.076650,0.076029,0.072647,0.075152,0.069372,0.064612,0.058496,0.055641,0.069084,0.079044,0.066286,0.070203,0.071116,0.055316,0.061192,0.057477,0.077310,0.067871