## Healthy

In [1]:
import csv
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\frontal_lobe\GSE61431

df1 = pd.read_csv('GSE61431_Age_fl_hc.csv')
df2 = pd.read_csv('GSE61431_Top2b_Age.csv')
df2.head(2)

Z:\Project_Top2B\April_2023\regionwise\frontal_lobe\GSE61431

,Sample_ID,Age,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,6042316024_R01C02,69,0.783647,0.090642,0.866361,0.141301,0.057352,0.862644,0.873811,0.066845,...,0.101461,0.888496,0.135375,0.112585,0.805163,0.902642,0.211552,0.094727,0.109248,0.851411
1,6042316024_R05C01,71,0.783619,0.079483,0.871209,0.132918,0.055086,0.859198,0.885479,0.077959,...,0.094492,0.918334,0.137261,0.105549,0.854186,0.897124,0.211990,0.110786,0.109832,0.875277

In [2]:
merged_df = pd.merge(df1, df2, how ='inner', on = df1.columns[0])
merged_df.to_csv('GSE61431_Top2b_fl.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(23, 4352)

,Sample_ID,Age_x,Age_y,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,6055432012_R02C02,71,71,0.783657,0.075478,0.866266,0.195541,0.060130,0.874226,0.891114,...,0.085840,0.897029,0.128858,0.226805,0.671828,0.907846,0.207363,0.094574,0.068945,0.902057
1,6055432012_R03C02,49,49,0.758202,0.064957,0.837387,0.209270,0.057222,0.865809,0.843831,...,0.118573,0.895693,0.131286,0.206515,0.797250,0.907439,0.201040,0.101501,0.089479,0.908236

## Diseased

In [3]:
df1 = pd.read_csv('GSE61431_Age_fl_Schizo.csv')
df2 = pd.read_csv('GSE61431_Schiz_Top2b.csv')
merged_df = pd.merge(df1, df2, how ='inner', on = 'Sample_ID')
merged_df.to_csv('GSE61431_Top2b_AD_fl.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(20, 4352)

,Sample_ID,Age_x,Age_y,cg00005072,cg00010266,cg00017203,cg00017489,cg00018024,cg00018539,cg00019511,...,cg27597926,cg27598168,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,6055432012_R01C01,76,76,0.655252,0.077581,0.778631,0.207276,0.060123,0.876964,0.874843,...,0.144468,0.896427,0.133851,0.332592,0.830696,0.911643,0.229198,0.122208,0.088903,0.900059
1,6055432012_R01C02,69,69,0.689109,0.085133,0.828079,0.212957,0.056929,0.849853,0.882227,...,0.128305,0.871450,0.131511,0.328949,0.795875,0.887390,0.205167,0.107249,0.082057,0.893944