In [4]:
import csv
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE105109

df1 = pd.read_csv('SampleID_Region_cb.csv')
df2 = pd.read_csv('GSE105109_Top2b_Age.csv')
df2.head(2)

Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE105109

,Sample_ID,Age,cg00010266,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,cg00029353,cg00030423,...,cg27569265,cg27597926,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,3998567035_R02C01,72,0.053486,0.090266,0.047286,0.696710,0.747023,0.061120,0.041779,0.041226,...,0.098649,0.075434,0.107490,0.082852,0.757628,0.793463,0.196295,0.098146,0.047320,0.702404
1,3998567035_R02C02,73,0.068088,0.095195,0.051092,0.800047,0.753772,0.068804,0.047275,0.034871,...,0.124165,0.069092,0.153465,0.111266,0.490703,0.782208,0.294890,0.086765,0.084147,0.676831

In [5]:
merged_df = pd.merge(df1, df2, how ='inner', on = df1.columns[0])
merged_df.to_csv('GSE105109_Top2b_cb.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

(56, 3824)

,Sample_ID,Age,cg00010266,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,cg00029353,cg00030423,...,cg27569265,cg27597926,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,3998567107_R01C01,88,0.050862,0.079246,0.071306,0.686413,0.703100,0.061161,0.074772,0.035830,...,0.116539,0.069947,0.114395,0.070653,0.749414,0.787851,0.204128,0.095212,0.068105,0.707947
1,3998567107_R01C02,88,0.079362,0.123970,0.058710,0.700640,0.776319,0.061387,0.066726,0.048138,...,0.156214,0.113543,0.137441,0.136945,0.421624,0.499539,0.315198,0.073085,0.097668,0.676073

In [2]:
import csv
import pandas as pd

%cd Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE105109

df1 = pd.read_csv('GSE105109_Sample_AD_cb.csv')
df2 = pd.read_csv('GSE105109_AD_Top2b_Age.csv')
merged_df = pd.merge(df1, df2, how ='inner', on = df1.columns[0])
merged_df.to_csv('GSE105109_Top2b_AD_cb.csv', index = 'False')
print(merged_df.shape)
merged_df.head(2)

Z:\Project_Top2B\April_2023\regionwise\cerebellum\GSE105109
(135, 3823)

,Sample_ID,cg00010266,cg00017489,cg00018024,cg00018539,cg00019511,cg00021539,cg00029353,cg00030423,cg00034416,...,cg27569265,cg27597926,cg27601855,cg27624319,cg27629898,cg27633533,cg27635069,cg27658416,cg27658967,cg27664120
0,3998567107_R02C01,0.064900,0.079427,0.061938,0.615045,0.710563,0.058529,0.049756,0.045647,0.055769,...,0.119411,0.079457,0.095483,0.097730,0.735215,0.854680,0.223134,0.099285,0.062868,0.717534
1,3998567107_R02C02,0.096679,0.099071,0.067148,0.734096,0.733726,0.078532,0.088218,0.045369,0.057075,...,0.192131,0.111622,0.158866,0.141743,0.353787,0.600749,0.281776,0.093674,0.089211,0.727145